import {
	WixBookingCategory,
	WixBrand,
	WixCampaign,
	WixContact,
	WixCoupon,
	WixCurrency,
	WixCustomField,
	WixExtendedBooking,
	WixForm,
	WixFormSubmission,
	WixGroupRequest,
	WixInventoryItem,
	WixLocation,
	WixManualTaxMapping,
	WixModerationRule,
	WixOrder,
	WixProduct,
	WixSiteFolder,
	WixTaxGroup,
} from './database';

export const WixSchema = {
	version: '1.0.0',
	entities: {
		contacts: WixContact,
		products: WixProduct,
		orders: WixOrder,
		inventoryItems: WixInventoryItem,
		coupons: WixCoupon,
		bookingCategories: WixBookingCategory,
		siteFolders: WixSiteFolder,
		campaigns: WixCampaign,
		forms: WixForm,
		formSubmissions: WixFormSubmission,
		locations: WixLocation,
		moderationRules: WixModerationRule,
		taxGroups: WixTaxGroup,
		extendedBookings: WixExtendedBooking,
		manualTaxMappings: WixManualTaxMapping,
		customFields: WixCustomField,
		groupRequests: WixGroupRequest,
		currencies: WixCurrency,
		brands: WixBrand,
	},
} as const;
