export type BorneoRiskLevel = 'read' | 'write' | 'destructive';

export type BorneoOperation = {
	readonly id: string;
	readonly name: string;
	readonly title: string;
	readonly group: string;
	readonly riskLevel: BorneoRiskLevel;
};

export const BORNEO_TOOLKIT_VERSION = '20260429_00' as const;

export const BORNEO_OPERATIONS = [
	{
		id: 'BORNEO_GET_CLOUD_ACCOUNT_BY_ID',
		name: 'getCloudAccountById',
		title: 'Get cloud account by id',
		group: 'accounts',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_POST_ACCOUNTS_WITH_FILTER_AND_SORT_OPTIONS',
		name: 'postAccountsWithFilterAndSortOptions',
		title: 'Post accounts with filter and sort options',
		group: 'accounts',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_RETRIEVE_ACCOUNT_DETAILS_BY_ID',
		name: 'retrieveAccountDetailsById',
		title: 'Retrieve account details by id',
		group: 'accounts',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_CREATE_NEW_ASSET',
		name: 'createNewAsset',
		title: 'Create new asset',
		group: 'assets',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_DELETE_ASSET_BY_ID',
		name: 'deleteAssetById',
		title: 'Delete asset by id',
		group: 'assets',
		riskLevel: 'destructive',
	},
	{
		id: 'BORNEO_FILTER_AND_SORT_ASSETS_LIST',
		name: 'filterAndSortAssetsList',
		title: 'Filter and sort assets list',
		group: 'assets',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_RETRIEVE_ASSET_BY_ID',
		name: 'retrieveAssetById',
		title: 'Retrieve asset by id',
		group: 'assets',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_UPDATE_ASSET_INFORMATION_BY_ID',
		name: 'updateAssetInformationById',
		title: 'Update asset information by id',
		group: 'assets',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_LIST_EVENTS_WITH_FILTERS',
		name: 'listEventsWithFilters',
		title: 'List events with filters',
		group: 'audit',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_POST_FILTERED_ACCESS_LOGS',
		name: 'postFilteredAccessLogs',
		title: 'Post filtered access logs',
		group: 'audit',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_POST_LOG_AUDIT_RECORDS_WITH_FILTER_CRITERIA',
		name: 'postLogAuditRecordsWithFilterCriteria',
		title: 'Post log audit records with filter criteria',
		group: 'audit',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_DELETE_DATA_BREACH_BY_ID',
		name: 'deleteDataBreachById',
		title: 'Delete data breach by id',
		group: 'breaches',
		riskLevel: 'destructive',
	},
	{
		id: 'BORNEO_EVALUATE_DATA_BREACH_IMPACT',
		name: 'evaluateDataBreachImpact',
		title: 'Evaluate data breach impact',
		group: 'breaches',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_FETCH_DATA_BREACH_EVALUATION',
		name: 'fetchDataBreachEvaluation',
		title: 'Fetch data breach evaluation',
		group: 'breaches',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_LIST_DATA_BREACH_FILTERS',
		name: 'listDataBreachFilters',
		title: 'List data breach filters',
		group: 'breaches',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_LIST_DATA_BREACHES_WITH_FILTERS',
		name: 'listDataBreachesWithFilters',
		title: 'List data breaches with filters',
		group: 'breaches',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_POST_DATA_BREACH_INFORMATION',
		name: 'postDataBreachInformation',
		title: 'Post data breach information',
		group: 'breaches',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_RETRIEVE_DATA_BREACH_BY_ID',
		name: 'retrieveDataBreachById',
		title: 'Retrieve data breach by id',
		group: 'breaches',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_UPDATE_DATA_BREACH_ENTRY',
		name: 'updateDataBreachEntry',
		title: 'Update data breach entry',
		group: 'breaches',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_CREATE_NEW_INFOTYPE_CATEGORY',
		name: 'createNewInfotypeCategory',
		title: 'Create new infotype category',
		group: 'categories',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_DELETE_CATEGORY_BY_LABEL',
		name: 'deleteCategoryByLabel',
		title: 'Delete category by label',
		group: 'categories',
		riskLevel: 'destructive',
	},
	{
		id: 'BORNEO_GET_CATEGORY_BY_LABEL',
		name: 'getCategoryByLabel',
		title: 'Get category by label',
		group: 'categories',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_UPDATE_CATEGORY_INFOTYPES',
		name: 'updateCategoryInfotypes',
		title: 'Update category infotypes',
		group: 'categories',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_POST_CONNECTOR_WITH_FILTERING_OPTIONS',
		name: 'postConnectorWithFilteringOptions',
		title: 'Post connector with filtering options',
		group: 'connectors',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_RETRIEVE_CONNECTOR_BY_ID',
		name: 'retrieveConnectorById',
		title: 'Retrieve connector by id',
		group: 'connectors',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_CREATE_DASHBOARD_USER',
		name: 'createDashboardUser',
		title: 'Create dashboard user',
		group: 'dashboard',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_DELETE_DASHBOARD_REPORT_BY_ID',
		name: 'deleteDashboardReportById',
		title: 'Delete dashboard report by id',
		group: 'dashboard',
		riskLevel: 'destructive',
	},
	{
		id: 'BORNEO_DISABLE_DASHBOARD_USER_BY_USERNAME',
		name: 'disableDashboardUserByUsername',
		title: 'Disable dashboard user by username',
		group: 'dashboard',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_DOWNLOAD_DASHBOARD_REPORT',
		name: 'downloadDashboardReport',
		title: 'Download dashboard report',
		group: 'dashboard',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_DOWNLOAD_DASHBOARD_REPORT_EDITION',
		name: 'downloadDashboardReportEdition',
		title: 'Download dashboard report edition',
		group: 'dashboard',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_ENABLE_DASHBOARD_USER',
		name: 'enableDashboardUser',
		title: 'Enable dashboard user',
		group: 'dashboard',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_FETCH_DASHBOARD_REPORT_BY_ID',
		name: 'fetchDashboardReportById',
		title: 'Fetch dashboard report by id',
		group: 'dashboard',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_GET_DASHBOARD_REPORT_EDITION_BY_ID',
		name: 'getDashboardReportEditionById',
		title: 'Get dashboard report edition by id',
		group: 'dashboard',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_LIST_DASHBOARD_REPORT_EDITIONS',
		name: 'listDashboardReportEditions',
		title: 'List dashboard report editions',
		group: 'dashboard',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_LIST_DASHBOARD_REPORTS_WITH_FILTERS',
		name: 'listDashboardReportsWithFilters',
		title: 'List dashboard reports with filters',
		group: 'dashboard',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_LIST_DASHBOARD_USERS_WITH_FILTERS',
		name: 'listDashboardUsersWithFilters',
		title: 'List dashboard users with filters',
		group: 'dashboard',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_POST_CURRENT_DASHBOARD_USER',
		name: 'postCurrentDashboardUser',
		title: 'Post current dashboard user',
		group: 'dashboard',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_POST_DASHBOARD_REPORT',
		name: 'postDashboardReport',
		title: 'Post dashboard report',
		group: 'dashboard',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_REMOVE_DASHBOARD_USER_BY_USERNAME',
		name: 'removeDashboardUserByUsername',
		title: 'Remove dashboard user by username',
		group: 'dashboard',
		riskLevel: 'destructive',
	},
	{
		id: 'BORNEO_RESET_DASHBOARD_USER_PASSWORD',
		name: 'resetDashboardUserPassword',
		title: 'Reset dashboard user password',
		group: 'dashboard',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_TRIGGER_DASHBOARD_REPORT_BY_REPORT_ID',
		name: 'triggerDashboardReportByReportId',
		title: 'Trigger dashboard report by report id',
		group: 'dashboard',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_UPDATE_DASHBOARD_USER_DETAILS',
		name: 'updateDashboardUserDetails',
		title: 'Update dashboard user details',
		group: 'dashboard',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_UPDATE_DASHBOARD_USER_ROLES',
		name: 'updateDashboardUserRoles',
		title: 'Update dashboard user roles',
		group: 'dashboard',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_CREATE_DEPARTMENT_WITH_TRANSLATIONS',
		name: 'createDepartmentWithTranslations',
		title: 'Create department with translations',
		group: 'departments',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_DELETE_DEPARTMENT_BY_ID',
		name: 'deleteDepartmentById',
		title: 'Delete department by id',
		group: 'departments',
		riskLevel: 'destructive',
	},
	{
		id: 'BORNEO_GET_DEPARTMENT_FILTER_LIST',
		name: 'getDepartmentFilterList',
		title: 'Get department filter list',
		group: 'departments',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_LIST_DEPARTMENTS_WITH_SORT_AND_PAGINATION',
		name: 'listDepartmentsWithSortAndPagination',
		title: 'List departments with sort and pagination',
		group: 'departments',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_RETRIEVE_DEPARTMENT_INFORMATION',
		name: 'retrieveDepartmentInformation',
		title: 'Retrieve department information',
		group: 'departments',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_UPDATE_DEPARTMENT_NAME',
		name: 'updateDepartmentName',
		title: 'Update department name',
		group: 'departments',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_CREATE_LEGAL_DOCUMENT_ENTRY',
		name: 'createLegalDocumentEntry',
		title: 'Create legal document entry',
		group: 'documents',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_DELETE_LEGAL_DOCUMENT_BY_ID',
		name: 'deleteLegalDocumentById',
		title: 'Delete legal document by id',
		group: 'documents',
		riskLevel: 'destructive',
	},
	{
		id: 'BORNEO_LIST_DISCOVERED_DOCUMENT',
		name: 'listDiscoveredDocument',
		title: 'List discovered document',
		group: 'documents',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_LIST_LEGAL_DOCUMENTS_WITH_PAGINATION',
		name: 'listLegalDocumentsWithPagination',
		title: 'List legal documents with pagination',
		group: 'documents',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_RETRIEVE_DISCOVERED_DOCUMENT_BY_ID',
		name: 'retrieveDiscoveredDocumentById',
		title: 'Retrieve discovered document by id',
		group: 'documents',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_RETRIEVE_LEGAL_DOCUMENT_BY_ID',
		name: 'retrieveLegalDocumentById',
		title: 'Retrieve legal document by id',
		group: 'documents',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_UPDATE_DISCOVERED_DOCUMENT_STATUS',
		name: 'updateDiscoveredDocumentStatus',
		title: 'Update discovered document status',
		group: 'documents',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_CREATE_DOMAIN_WITH_POLLING_FREQUENCY',
		name: 'createDomainWithPollingFrequency',
		title: 'Create domain with polling frequency',
		group: 'domains',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_DELETE_DOMAIN_BY_ID',
		name: 'deleteDomainById',
		title: 'Delete domain by id',
		group: 'domains',
		riskLevel: 'destructive',
	},
	{
		id: 'BORNEO_GET_DOMAIN_BY_ID',
		name: 'getDomainById',
		title: 'Get domain by id',
		group: 'domains',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_LIST_DOMAINS_WITH_PAGINATION_AND_SORTING',
		name: 'listDomainsWithPaginationAndSorting',
		title: 'List domains with pagination and sorting',
		group: 'domains',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_POLL_DOMAIN_BY_ID',
		name: 'pollDomainById',
		title: 'Poll domain by id',
		group: 'domains',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_UPDATE_DOMAIN_DETAILS',
		name: 'updateDomainDetails',
		title: 'Update domain details',
		group: 'domains',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_CREATE_EMPLOYEE_WITH_JSON_PAYLOAD',
		name: 'createEmployeeWithJsonPayload',
		title: 'Create employee with json payload',
		group: 'employees',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_DELETE_EMPLOYEE_BY_ID',
		name: 'deleteEmployeeById',
		title: 'Delete employee by id',
		group: 'employees',
		riskLevel: 'destructive',
	},
	{
		id: 'BORNEO_FILTER_EMPLOYEE_LIST',
		name: 'filterEmployeeList',
		title: 'Filter employee list',
		group: 'employees',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_LIST_EMPLOYEES_WITH_FILTERS',
		name: 'listEmployeesWithFilters',
		title: 'List employees with filters',
		group: 'employees',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_RETRIEVE_EMPLOYEE_DETAILS_BY_ID',
		name: 'retrieveEmployeeDetailsById',
		title: 'Retrieve employee details by id',
		group: 'employees',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_UPDATE_EMPLOYEE_BY_ID',
		name: 'updateEmployeeById',
		title: 'Update employee by id',
		group: 'employees',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_CREATE_HEADQUARTER_ENTRY',
		name: 'createHeadquarterEntry',
		title: 'Create headquarter entry',
		group: 'headquarters',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_DELETE_HEADQUARTERS_BY_ID',
		name: 'deleteHeadquartersById',
		title: 'Delete headquarters by id',
		group: 'headquarters',
		riskLevel: 'destructive',
	},
	{
		id: 'BORNEO_GET_HEADQUARTERS_BY_ID',
		name: 'getHeadquartersById',
		title: 'Get headquarters by id',
		group: 'headquarters',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_LIST_HEADQUARTERS_WITH_SORTING',
		name: 'listHeadquartersWithSorting',
		title: 'List headquarters with sorting',
		group: 'headquarters',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_UPDATE_HEADQUARTER_DETAILS_BY_ID',
		name: 'updateHeadquarterDetailsById',
		title: 'Update headquarter details by id',
		group: 'headquarters',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_LIST_DISCOVERED_INFOTYPES',
		name: 'listDiscoveredInfotypes',
		title: 'List discovered infotypes',
		group: 'infotypes',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_RETRIEVE_DISCOVERED_INFOTYPE_BY_ID',
		name: 'retrieveDiscoveredInfotypeById',
		title: 'Retrieve discovered infotype by id',
		group: 'infotypes',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_UPDATE_DISCOVERED_INFOTYPE_STATUS',
		name: 'updateDiscoveredInfotypeStatus',
		title: 'Update discovered infotype status',
		group: 'infotypes',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_LIST_FILTERED_SORTED_CATEGORIES',
		name: 'listFilteredSortedCategories',
		title: 'List filtered sorted categories',
		group: 'misc',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_LIST_ISSUES_WITH_FILTERS',
		name: 'listIssuesWithFilters',
		title: 'List issues with filters',
		group: 'misc',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_RETRIEVE_ERROR_DETAILS_BY_ID',
		name: 'retrieveErrorDetailsById',
		title: 'Retrieve error details by id',
		group: 'misc',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_RETRIEVE_ISSUE_BY_ID',
		name: 'retrieveIssueById',
		title: 'Retrieve issue by id',
		group: 'misc',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_SUBMIT_CHAT_FEEDBACK',
		name: 'submitChatFeedback',
		title: 'Submit chat feedback',
		group: 'misc',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_CREATE_DPIA_FOR_PROCESSING_ACTIVITY',
		name: 'createDpiaForProcessingActivity',
		title: 'Create dpia for processing activity',
		group: 'processing',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_CREATE_PROCESSING_ACTIVITY',
		name: 'createProcessingActivity',
		title: 'Create processing activity',
		group: 'processing',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_CREATE_PROCESSING_ACTIVITY_THRESHOLD',
		name: 'createProcessingActivityThreshold',
		title: 'Create processing activity threshold',
		group: 'processing',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_CREATE_THRESHOLD_FOR_PROCESSING_ACTIVITY',
		name: 'createThresholdForProcessingActivity',
		title: 'Create threshold for processing activity',
		group: 'processing',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_DELETE_DPIA_BY_ID',
		name: 'deleteDpiaById',
		title: 'Delete dpia by id',
		group: 'processing',
		riskLevel: 'destructive',
	},
	{
		id: 'BORNEO_DELETE_LOPDP_THRESHOLD_BY_ID',
		name: 'deleteLopdpThresholdById',
		title: 'Delete lopdp threshold by id',
		group: 'processing',
		riskLevel: 'destructive',
	},
	{
		id: 'BORNEO_DELETE_PROCESSING_ACTIVITY_BY_ID',
		name: 'deleteProcessingActivityById',
		title: 'Delete processing activity by id',
		group: 'processing',
		riskLevel: 'destructive',
	},
	{
		id: 'BORNEO_DELETE_THRESHOLD_BY_ID',
		name: 'deleteThresholdById',
		title: 'Delete threshold by id',
		group: 'processing',
		riskLevel: 'destructive',
	},
	{
		id: 'BORNEO_EXPORT_PROCESSING_ACTIVITIES_LIST',
		name: 'exportProcessingActivitiesList',
		title: 'Export processing activities list',
		group: 'processing',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_GET_THRESHOLD_BY_ID',
		name: 'getThresholdById',
		title: 'Get threshold by id',
		group: 'processing',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_LIST_PROCESSING_ACTIVITIES',
		name: 'listProcessingActivities',
		title: 'List processing activities',
		group: 'processing',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_LIST_PROCESSING_ACTIVITIES_FILTERS',
		name: 'listProcessingActivitiesFilters',
		title: 'List processing activities filters',
		group: 'processing',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_LIST_TOMS_WITH_FILTER_AND_PAGINATION_OPTIONS',
		name: 'listTomsWithFilterAndPaginationOptions',
		title: 'List toms with filter and pagination options',
		group: 'processing',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_PUT_TOM_STATUS_AND_NOTE',
		name: 'putTomStatusAndNote',
		title: 'Put tom status and note',
		group: 'processing',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_RETRIEVE_DPIA_BY_ID',
		name: 'retrieveDpiaById',
		title: 'Retrieve dpia by id',
		group: 'processing',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_RETRIEVE_LOPDP_THRESHOLD_BY_ID',
		name: 'retrieveLopdpThresholdById',
		title: 'Retrieve lopdp threshold by id',
		group: 'processing',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_RETRIEVE_PROCESSING_ACTIVITY_BY_ID',
		name: 'retrieveProcessingActivityById',
		title: 'Retrieve processing activity by id',
		group: 'processing',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_RETRIEVE_TOM_BY_ID',
		name: 'retrieveTomById',
		title: 'Retrieve tom by id',
		group: 'processing',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_UPDATE_DPIA_BY_ID',
		name: 'updateDpiaById',
		title: 'Update dpia by id',
		group: 'processing',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_UPDATE_LOPDP_THRESHOLD_BY_ID',
		name: 'updateLopdpThresholdById',
		title: 'Update lopdp threshold by id',
		group: 'processing',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_UPDATE_PROCESSING_ACTIVITY_DETAILS',
		name: 'updateProcessingActivityDetails',
		title: 'Update processing activity details',
		group: 'processing',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_UPDATE_THRESHOLD_BY_ID',
		name: 'updateThresholdById',
		title: 'Update threshold by id',
		group: 'processing',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_ADD_DISCOVERED_RECIPIENTS',
		name: 'addDiscoveredRecipients',
		title: 'Add discovered recipients',
		group: 'recipients',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_ARCHIVE_DISCOVERED_RECIPIENT',
		name: 'archiveDiscoveredRecipient',
		title: 'Archive discovered recipient',
		group: 'recipients',
		riskLevel: 'destructive',
	},
	{
		id: 'BORNEO_CREATE_RECIPIENT_WITH_DETAILS',
		name: 'createRecipientWithDetails',
		title: 'Create recipient with details',
		group: 'recipients',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_DELETE_RECIPIENT_BY_ID',
		name: 'deleteRecipientById',
		title: 'Delete recipient by id',
		group: 'recipients',
		riskLevel: 'destructive',
	},
	{
		id: 'BORNEO_EXPORT_RECIPIENTS_LIST_WITH_FILTER',
		name: 'exportRecipientsListWithFilter',
		title: 'Export recipients list with filter',
		group: 'recipients',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_FILTER_RECIPIENTS_LIST',
		name: 'filterRecipientsList',
		title: 'Filter recipients list',
		group: 'recipients',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_LIST_DISCOVERED_RECIPIENTS',
		name: 'listDiscoveredRecipients',
		title: 'List discovered recipients',
		group: 'recipients',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_LIST_FILTER_OPTIONS_FOR_RECIPIENTS',
		name: 'listFilterOptionsForRecipients',
		title: 'List filter options for recipients',
		group: 'recipients',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_LIST_OR_FILTER_RECIPIENTS',
		name: 'listOrFilterRecipients',
		title: 'List or filter recipients',
		group: 'recipients',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_POST_DISCOVERED_RECIPIENT_BY_ID',
		name: 'postDiscoveredRecipientById',
		title: 'Post discovered recipient by id',
		group: 'recipients',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_RETRIEVE_DISCOVERED_RECIPIENT_BY_ID',
		name: 'retrieveDiscoveredRecipientById',
		title: 'Retrieve discovered recipient by id',
		group: 'recipients',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_RETRIEVE_RECIPIENT_DETAILS',
		name: 'retrieveRecipientDetails',
		title: 'Retrieve recipient details',
		group: 'recipients',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_RETRIEVE_RECIPIENT_PROCESSING_ACTIVITIES',
		name: 'retrieveRecipientProcessingActivities',
		title: 'Retrieve recipient processing activities',
		group: 'recipients',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_UPDATE_DASHBOARD_REPORT_FREQUENCY_AND_RECIPIENTS',
		name: 'updateDashboardReportFrequencyAndRecipients',
		title: 'Update dashboard report frequency and recipients',
		group: 'recipients',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_UPDATE_RECIPIENT_DETAILS_BY_ID',
		name: 'updateRecipientDetailsById',
		title: 'Update recipient details by id',
		group: 'recipients',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_UPDATE_RECIPIENT_STATUS_VIA_ID',
		name: 'updateRecipientStatusViaId',
		title: 'Update recipient status via id',
		group: 'recipients',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_DELETE_TAG_FROM_RESOURCE',
		name: 'deleteTagFromResource',
		title: 'Delete tag from resource',
		group: 'resources',
		riskLevel: 'destructive',
	},
	{
		id: 'BORNEO_EXPORT_FILTERED_LEAF_RESOURCES',
		name: 'exportFilteredLeafResources',
		title: 'Export filtered leaf resources',
		group: 'resources',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_EXPORT_INVENTORY_RESOURCE_LIST',
		name: 'exportInventoryResourceList',
		title: 'Export inventory resource list',
		group: 'resources',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_GET_RESOURCE_INVENTORY_BY_ID',
		name: 'getResourceInventoryById',
		title: 'Get resource inventory by id',
		group: 'resources',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_LIST_INVENTORY_RESOURCES_WITH_FILTERS',
		name: 'listInventoryResourcesWithFilters',
		title: 'List inventory resources with filters',
		group: 'resources',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_LIST_LEAF_RESOURCES_WITH_FILTERS',
		name: 'listLeafResourcesWithFilters',
		title: 'List leaf resources with filters',
		group: 'resources',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_POST_CLASSIFICATION_STATS',
		name: 'postClassificationStats',
		title: 'Post classification stats',
		group: 'resources',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_POST_RESOURCE_LINEAGE_FILTER',
		name: 'postResourceLineageFilter',
		title: 'Post resource lineage filter',
		group: 'resources',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_POST_RESOURCE_STATS_WITH_DELETED_RESOURCES',
		name: 'postResourceStatsWithDeletedResources',
		title: 'Post resource stats with deleted resources',
		group: 'resources',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_RETRIEVE_DATA_RESOURCE_STATISTICS',
		name: 'retrieveDataResourceStatistics',
		title: 'Retrieve data resource statistics',
		group: 'resources',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_RETRIEVE_RESOURCE_CATALOG_BY_ID',
		name: 'retrieveResourceCatalogById',
		title: 'Retrieve resource catalog by id',
		group: 'resources',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_RETRIEVE_RESOURCE_COLUMNS',
		name: 'retrieveResourceColumns',
		title: 'Retrieve resource columns',
		group: 'resources',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_ACCESS_SCAN_ITERATION_BY_ID',
		name: 'accessScanIterationById',
		title: 'Access scan iteration by id',
		group: 'scans',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_CREATE_AND_SCHEDULE_CLOUD_RESOURCE_SCAN',
		name: 'createAndScheduleCloudResourceScan',
		title: 'Create and schedule cloud resource scan',
		group: 'scans',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_EXPORT_INSIGHT_PAGE_USING_SCAN_ID',
		name: 'exportInsightPageUsingScanId',
		title: 'Export insight page using scanid',
		group: 'scans',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_FILTER_AND_LIST_INSPECTION_RESULTS',
		name: 'filterAndListInspectionResults',
		title: 'Filter and list inspection results',
		group: 'scans',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_GET_INSIGHT_BY_TYPE_AND_ID',
		name: 'getInsightByTypeAndId',
		title: 'Get insight by type and id',
		group: 'scans',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_GET_SCAN_BY_SCAN_ID',
		name: 'getScanByScanId',
		title: 'Get scan by scanid',
		group: 'scans',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_LIST_ERROR_DETAILS_FROM_FILTERED_SCAN_ITERATIONS',
		name: 'listErrorDetailsFromFilteredScanIterations',
		title: 'List error details from filtered scan iterations',
		group: 'scans',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_LIST_INSIGHT_FILTERS',
		name: 'listInsightFilters',
		title: 'List insight filters',
		group: 'scans',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_LIST_SCAN_EXECUTION_RESULTS',
		name: 'listScanExecutionResults',
		title: 'List scan execution results',
		group: 'scans',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_LIST_SCAN_ITERATIONS_WITH_FILTER',
		name: 'listScanIterationsWithFilter',
		title: 'List scan iterations with filter',
		group: 'scans',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_LIST_SCANS_WITH_FILTERS',
		name: 'listScansWithFilters',
		title: 'List scans with filters',
		group: 'scans',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_MARK_SCAN_FALSE_POSITIVES_BY_ID',
		name: 'markScanFalsePositivesById',
		title: 'Mark scan false positives by id',
		group: 'scans',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_PAUSE_SCAN_BY_ID',
		name: 'pauseScanById',
		title: 'Pause scan by id',
		group: 'scans',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_POST_SCAN_RESOURCE_STATUS',
		name: 'postScanResourceStatus',
		title: 'Post scan resource status',
		group: 'scans',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_RESUME_SCAN_BY_ID',
		name: 'resumeScanById',
		title: 'Resume scan by id',
		group: 'scans',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_SCAN_LEGAL_DOCUMENT_BY_ID',
		name: 'scanLegalDocumentById',
		title: 'Scan legal document byid',
		group: 'scans',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_STOP_SCAN_VIA_SCAN_ID',
		name: 'stopScanViaScanId',
		title: 'Stop scan via scanid',
		group: 'scans',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_SUBMIT_DETAILED_SCAN_RESULTS',
		name: 'submitDetailedScanResults',
		title: 'Submit detailed scan results',
		group: 'scans',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_POST_SUPPORT_CHAT_QUERY',
		name: 'postSupportChatQuery',
		title: 'Post support chat query',
		group: 'support',
		riskLevel: 'write',
	},
	{
		id: 'BORNEO_GET_USER_PROFILE_BY_ID',
		name: 'getUserProfileById',
		title: 'Get user profile by id',
		group: 'users',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_LIST_USER_PROFILE_WITH_FILTERS_AND_SORTING',
		name: 'listUserProfileWithFiltersAndSorting',
		title: 'List user profile with filters and sorting',
		group: 'users',
		riskLevel: 'read',
	},
	{
		id: 'BORNEO_VERIFY_EMAIL_WITH_ID_AND_TOKEN',
		name: 'verifyEmailWithIdAndToken',
		title: 'Verify email with id and token',
		group: 'users',
		riskLevel: 'write',
	},
] as const satisfies readonly BorneoOperation[];

export type BorneoOperationName = (typeof BORNEO_OPERATIONS)[number]['name'];
export type BorneoOperationId = (typeof BORNEO_OPERATIONS)[number]['id'];
export type BorneoOperationGroup = (typeof BORNEO_OPERATIONS)[number]['group'];

export const BORNEO_OPERATION_COUNT = BORNEO_OPERATIONS.length;
export const BORNEO_OPERATION_IDS = BORNEO_OPERATIONS.map(
	(operation) => operation.id,
);

export const BORNEO_OPERATION_BY_NAME = Object.fromEntries(
	BORNEO_OPERATIONS.map((operation) => [operation.name, operation]),
) as Record<BorneoOperationName, (typeof BORNEO_OPERATIONS)[number]>;
