import { z } from 'zod';

// PullZoneAddModel (core spec) — Name is required by the API
export const PullZoneAddDetailsSchema = z.looseObject({
	OriginUrl: z.string().optional(),
	AllowedReferrers: z.array(z.unknown()).optional(),
	BlockedReferrers: z.array(z.unknown()).optional(),
	BlockNoneReferrer: z.boolean().optional(),
	BlockedIps: z.array(z.unknown()).optional(),
	EnableGeoZoneUS: z.boolean().optional(),
	EnableGeoZoneEU: z.boolean().optional(),
	EnableGeoZoneASIA: z.boolean().optional(),
	EnableGeoZoneSA: z.boolean().optional(),
	EnableGeoZoneAF: z.boolean().optional(),
	IpFamilyPolicy: z.number().int().optional(),
	BlockRootPathAccess: z.boolean().optional(),
	BlockPostRequests: z.boolean().optional(),
	EnableQueryStringOrdering: z.boolean().optional(),
	EnableWebpVary: z.boolean().optional(),
	EnableAvifVary: z.boolean().optional(),
	EnableMobileVary: z.boolean().optional(),
	EnableCountryCodeVary: z.boolean().optional(),
	EnableCountryStateCodeVary: z.boolean().optional(),
	EnableHostnameVary: z.boolean().optional(),
	EnableCacheSlice: z.boolean().optional(),
	ZoneSecurityEnabled: z.boolean().optional(),
	ZoneSecurityIncludeHashRemoteIP: z.boolean().optional(),
	IgnoreQueryStrings: z.boolean().optional(),
	MonthlyBandwidthLimit: z.number().optional(),
	AccessControlOriginHeaderExtensions: z.array(z.unknown()).optional(),
	EnableAccessControlOriginHeader: z.boolean().optional(),
	DisableCookies: z.boolean().optional(),
	BudgetRedirectedCountries: z.array(z.unknown()).optional(),
	BlockedCountries: z.array(z.unknown()).optional(),
	CacheControlMaxAgeOverride: z.number().optional(),
	CacheControlPublicMaxAgeOverride: z.number().optional(),
	CacheControlBrowserMaxAgeOverride: z.number().optional(),
	AddHostHeader: z.boolean().optional(),
	AddCanonicalHeader: z.boolean().optional(),
	EnableLogging: z.boolean().optional(),
	LoggingIPAnonymizationEnabled: z.boolean().optional(),
	PermaCacheStorageZoneId: z.number().optional(),
	PermaCacheType: z.number().int().optional(),
	AWSSigningEnabled: z.boolean().optional(),
	AWSSigningKey: z.string().optional(),
	AWSSigningRegionName: z.string().optional(),
	AWSSigningSecret: z.string().optional(),
	EnableOriginShield: z.boolean().optional(),
	OriginShieldZoneCode: z.string().optional(),
	EnableTLS1: z.boolean().optional(),
	EnableTLS1_1: z.boolean().optional(),
	TlsSecurityLevel: z.number().int().optional(),
	CacheErrorResponses: z.boolean().optional(),
	VerifyOriginSSL: z.boolean().optional(),
	LogForwardingEnabled: z.boolean().optional(),
	LogForwardingHostname: z.string().optional(),
	LogForwardingPort: z.number().optional(),
	LogForwardingToken: z.string().optional(),
	LogForwardingProtocol: z.number().int().optional(),
	LoggingSaveToStorage: z.boolean().optional(),
	LoggingStorageZoneId: z.number().optional(),
	FollowRedirects: z.boolean().optional(),
	ConnectionLimitPerIPCount: z.number().optional(),
	RequestLimit: z.number().optional(),
	LimitRateAfter: z.number().optional(),
	LimitRatePerSecond: z.number().optional(),
	BurstSize: z.number().optional(),
	ErrorPageEnableCustomCode: z.boolean().optional(),
	ErrorPageCustomCode: z.string().optional(),
	ErrorPageEnableStatuspageWidget: z.boolean().optional(),
	ErrorPageStatuspageCode: z.string().optional(),
	ErrorPageWhitelabel: z.boolean().optional(),
	OptimizerEnabled: z.boolean().optional(),
	OptimizerTunnelEnabled: z.boolean().optional(),
	OptimizerDesktopMaxWidth: z.number().optional(),
	OptimizerMobileMaxWidth: z.number().optional(),
	OptimizerImageQuality: z.number().optional(),
	OptimizerMobileImageQuality: z.number().optional(),
	OptimizerEnableWebP: z.boolean().optional(),
	OptimizerPrerenderHtml: z.boolean().optional(),
	OptimizerHtmlToMarkdown: z.number().int().optional(),
	OptimizerLlmsTxt: z.boolean().optional(),
	OptimizerEnableManipulationEngine: z.boolean().optional(),
	OptimizerMinifyCSS: z.boolean().optional(),
	OptimizerMinifyJavaScript: z.boolean().optional(),
	OptimizerWatermarkEnabled: z.boolean().optional(),
	OptimizerWatermarkUrl: z.string().optional(),
	OptimizerWatermarkPosition: z.number().int().optional(),
	OptimizerWatermarkOffset: z.number().optional(),
	OptimizerWatermarkMinImageSize: z.number().optional(),
	OptimizerAutomaticOptimizationEnabled: z.boolean().optional(),
	OptimizerClasses: z.array(z.unknown()).optional(),
	OptimizerForceClasses: z.boolean().optional(),
	OptimizerStaticHtmlEnabled: z.boolean().optional(),
	OptimizerStaticHtmlWordPressPath: z.string().optional(),
	OptimizerStaticHtmlWordPressBypassCookie: z.string().optional(),
	Type: z.number().int().optional(),
	OriginRetries: z.number().optional(),
	OriginConnectTimeout: z.number().optional(),
	OriginResponseTimeout: z.number().optional(),
	UseStaleWhileUpdating: z.boolean().optional(),
	UseStaleWhileOffline: z.boolean().optional(),
	OriginRetry5XXResponses: z.boolean().optional(),
	OriginRetryConnectionTimeout: z.boolean().optional(),
	OriginRetryResponseTimeout: z.boolean().optional(),
	OriginRetryDelay: z.number().optional(),
	DnsOriginPort: z.number().optional(),
	DnsOriginScheme: z.string().optional(),
	QueryStringVaryParameters: z.array(z.unknown()).optional(),
	OriginShieldEnableConcurrencyLimit: z.boolean().optional(),
	OriginShieldMaxConcurrentRequests: z.number().optional(),
	EnableCookieVary: z.boolean().optional(),
	CookieVaryParameters: z.array(z.unknown()).optional(),
	EnableSafeHop: z.boolean().optional(),
	OriginShieldQueueMaxWaitTime: z.number().optional(),
	OriginShieldMaxQueuedRequests: z.number().optional(),
	UseBackgroundUpdate: z.boolean().optional(),
	EnableAutoSSL: z.boolean().optional(),
	LogAnonymizationType: z.number().int().optional(),
	StorageZoneId: z.number().optional(),
	EdgeScriptId: z.number().optional(),
	MiddlewareScriptId: z.number().optional(),
	EdgeScriptExecutionPhase: z.number().int().optional(),
	OriginType: z.number().int().optional(),
	MagicContainersAppId: z.string().optional(),
	MagicContainersEndpointId: z.string().optional(),
	LogFormat: z.number().int().optional(),
	LogForwardingFormat: z.number().int().optional(),
	ShieldDDosProtectionType: z.number().int().optional(),
	ShieldDDosProtectionEnabled: z.boolean().optional(),
	OriginHostHeader: z.string().optional(),
	EnableSmartCache: z.boolean().optional(),
	EnableRequestCoalescing: z.boolean().optional(),
	RequestCoalescingTimeout: z.number().optional(),
	DisableLetsEncrypt: z.boolean().optional(),
	EnableBunnyImageAi: z.boolean().optional(),
	BunnyAiImageBlueprints: z.array(z.unknown()).optional(),
	PreloadingScreenEnabled: z.boolean().optional(),
	PreloadingScreenCode: z.string().optional(),
	PreloadingScreenLogoUrl: z.string().optional(),
	PreloadingScreenShowOnFirstVisit: z.boolean().optional(),
	PreloadingScreenTheme: z.number().int().optional(),
	PreloadingScreenCodeEnabled: z.boolean().optional(),
	PreloadingScreenDelay: z.number().optional(),
	RoutingFilters: z.array(z.unknown()).optional(),
	StickySessionType: z.number().int().optional(),
	StickySessionCookieName: z.string().optional(),
	StickySessionClientHeaders: z.string().optional(),
	OptimizerEnableUpscaling: z.boolean().optional(),
	EnableWebSockets: z.boolean().optional(),
	MaxWebSocketConnections: z.number().optional(),
	CacheKeyHeaders: z.string().optional(),
	LoadBalancerId: z.number().optional(),
	Name: z.string(),
});
export type PullZoneAddDetails = z.infer<typeof PullZoneAddDetailsSchema>;

// PullZoneSettingsModel (core spec)
export const PullZoneSettingsDetailsSchema = z.looseObject({
	OriginUrl: z.string().optional(),
	AllowedReferrers: z.array(z.unknown()).optional(),
	BlockedReferrers: z.array(z.unknown()).optional(),
	BlockNoneReferrer: z.boolean().optional(),
	BlockedIps: z.array(z.unknown()).optional(),
	EnableGeoZoneUS: z.boolean().optional(),
	EnableGeoZoneEU: z.boolean().optional(),
	EnableGeoZoneASIA: z.boolean().optional(),
	EnableGeoZoneSA: z.boolean().optional(),
	EnableGeoZoneAF: z.boolean().optional(),
	IpFamilyPolicy: z.number().int().optional(),
	BlockRootPathAccess: z.boolean().optional(),
	BlockPostRequests: z.boolean().optional(),
	EnableQueryStringOrdering: z.boolean().optional(),
	EnableWebpVary: z.boolean().optional(),
	EnableAvifVary: z.boolean().optional(),
	EnableMobileVary: z.boolean().optional(),
	EnableCountryCodeVary: z.boolean().optional(),
	EnableCountryStateCodeVary: z.boolean().optional(),
	EnableHostnameVary: z.boolean().optional(),
	EnableCacheSlice: z.boolean().optional(),
	ZoneSecurityEnabled: z.boolean().optional(),
	ZoneSecurityIncludeHashRemoteIP: z.boolean().optional(),
	IgnoreQueryStrings: z.boolean().optional(),
	MonthlyBandwidthLimit: z.number().optional(),
	AccessControlOriginHeaderExtensions: z.array(z.unknown()).optional(),
	EnableAccessControlOriginHeader: z.boolean().optional(),
	DisableCookies: z.boolean().optional(),
	BudgetRedirectedCountries: z.array(z.unknown()).optional(),
	BlockedCountries: z.array(z.unknown()).optional(),
	CacheControlMaxAgeOverride: z.number().optional(),
	CacheControlPublicMaxAgeOverride: z.number().optional(),
	CacheControlBrowserMaxAgeOverride: z.number().optional(),
	AddHostHeader: z.boolean().optional(),
	AddCanonicalHeader: z.boolean().optional(),
	EnableLogging: z.boolean().optional(),
	LoggingIPAnonymizationEnabled: z.boolean().optional(),
	PermaCacheStorageZoneId: z.number().optional(),
	PermaCacheType: z.number().int().optional(),
	AWSSigningEnabled: z.boolean().optional(),
	AWSSigningKey: z.string().optional(),
	AWSSigningRegionName: z.string().optional(),
	AWSSigningSecret: z.string().optional(),
	EnableOriginShield: z.boolean().optional(),
	OriginShieldZoneCode: z.string().optional(),
	EnableTLS1: z.boolean().optional(),
	EnableTLS1_1: z.boolean().optional(),
	TlsSecurityLevel: z.number().int().optional(),
	CacheErrorResponses: z.boolean().optional(),
	VerifyOriginSSL: z.boolean().optional(),
	LogForwardingEnabled: z.boolean().optional(),
	LogForwardingHostname: z.string().optional(),
	LogForwardingPort: z.number().optional(),
	LogForwardingToken: z.string().optional(),
	LogForwardingProtocol: z.number().int().optional(),
	LoggingSaveToStorage: z.boolean().optional(),
	LoggingStorageZoneId: z.number().optional(),
	FollowRedirects: z.boolean().optional(),
	ConnectionLimitPerIPCount: z.number().optional(),
	RequestLimit: z.number().optional(),
	LimitRateAfter: z.number().optional(),
	LimitRatePerSecond: z.number().optional(),
	BurstSize: z.number().optional(),
	ErrorPageEnableCustomCode: z.boolean().optional(),
	ErrorPageCustomCode: z.string().optional(),
	ErrorPageEnableStatuspageWidget: z.boolean().optional(),
	ErrorPageStatuspageCode: z.string().optional(),
	ErrorPageWhitelabel: z.boolean().optional(),
	OptimizerEnabled: z.boolean().optional(),
	OptimizerTunnelEnabled: z.boolean().optional(),
	OptimizerDesktopMaxWidth: z.number().optional(),
	OptimizerMobileMaxWidth: z.number().optional(),
	OptimizerImageQuality: z.number().optional(),
	OptimizerMobileImageQuality: z.number().optional(),
	OptimizerEnableWebP: z.boolean().optional(),
	OptimizerPrerenderHtml: z.boolean().optional(),
	OptimizerHtmlToMarkdown: z.number().int().optional(),
	OptimizerLlmsTxt: z.boolean().optional(),
	OptimizerEnableManipulationEngine: z.boolean().optional(),
	OptimizerMinifyCSS: z.boolean().optional(),
	OptimizerMinifyJavaScript: z.boolean().optional(),
	OptimizerWatermarkEnabled: z.boolean().optional(),
	OptimizerWatermarkUrl: z.string().optional(),
	OptimizerWatermarkPosition: z.number().int().optional(),
	OptimizerWatermarkOffset: z.number().optional(),
	OptimizerWatermarkMinImageSize: z.number().optional(),
	OptimizerAutomaticOptimizationEnabled: z.boolean().optional(),
	OptimizerClasses: z.array(z.unknown()).optional(),
	OptimizerForceClasses: z.boolean().optional(),
	OptimizerStaticHtmlEnabled: z.boolean().optional(),
	OptimizerStaticHtmlWordPressPath: z.string().optional(),
	OptimizerStaticHtmlWordPressBypassCookie: z.string().optional(),
	Type: z.number().int().optional(),
	OriginRetries: z.number().optional(),
	OriginConnectTimeout: z.number().optional(),
	OriginResponseTimeout: z.number().optional(),
	UseStaleWhileUpdating: z.boolean().optional(),
	UseStaleWhileOffline: z.boolean().optional(),
	OriginRetry5XXResponses: z.boolean().optional(),
	OriginRetryConnectionTimeout: z.boolean().optional(),
	OriginRetryResponseTimeout: z.boolean().optional(),
	OriginRetryDelay: z.number().optional(),
	DnsOriginPort: z.number().optional(),
	DnsOriginScheme: z.string().optional(),
	QueryStringVaryParameters: z.array(z.unknown()).optional(),
	OriginShieldEnableConcurrencyLimit: z.boolean().optional(),
	OriginShieldMaxConcurrentRequests: z.number().optional(),
	EnableCookieVary: z.boolean().optional(),
	CookieVaryParameters: z.array(z.unknown()).optional(),
	EnableSafeHop: z.boolean().optional(),
	OriginShieldQueueMaxWaitTime: z.number().optional(),
	OriginShieldMaxQueuedRequests: z.number().optional(),
	UseBackgroundUpdate: z.boolean().optional(),
	EnableAutoSSL: z.boolean().optional(),
	LogAnonymizationType: z.number().int().optional(),
	StorageZoneId: z.number().optional(),
	EdgeScriptId: z.number().optional(),
	MiddlewareScriptId: z.number().optional(),
	EdgeScriptExecutionPhase: z.number().int().optional(),
	OriginType: z.number().int().optional(),
	MagicContainersAppId: z.string().optional(),
	MagicContainersEndpointId: z.string().optional(),
	LogFormat: z.number().int().optional(),
	LogForwardingFormat: z.number().int().optional(),
	ShieldDDosProtectionType: z.number().int().optional(),
	ShieldDDosProtectionEnabled: z.boolean().optional(),
	OriginHostHeader: z.string().optional(),
	EnableSmartCache: z.boolean().optional(),
	EnableRequestCoalescing: z.boolean().optional(),
	RequestCoalescingTimeout: z.number().optional(),
	DisableLetsEncrypt: z.boolean().optional(),
	EnableBunnyImageAi: z.boolean().optional(),
	BunnyAiImageBlueprints: z.array(z.unknown()).optional(),
	PreloadingScreenEnabled: z.boolean().optional(),
	PreloadingScreenCode: z.string().optional(),
	PreloadingScreenLogoUrl: z.string().optional(),
	PreloadingScreenShowOnFirstVisit: z.boolean().optional(),
	PreloadingScreenTheme: z.number().int().optional(),
	PreloadingScreenCodeEnabled: z.boolean().optional(),
	PreloadingScreenDelay: z.number().optional(),
	RoutingFilters: z.array(z.unknown()).optional(),
	StickySessionType: z.number().int().optional(),
	StickySessionCookieName: z.string().optional(),
	StickySessionClientHeaders: z.string().optional(),
	OptimizerEnableUpscaling: z.boolean().optional(),
	EnableWebSockets: z.boolean().optional(),
	MaxWebSocketConnections: z.number().optional(),
	CacheKeyHeaders: z.string().optional(),
	LoadBalancerId: z.number().optional(),
});
export type PullZoneSettingsDetails = z.infer<
	typeof PullZoneSettingsDetailsSchema
>;

// StorageZoneModelAdd (core spec) — Name and Region are required by the API
export const StorageZoneAddDetailsSchema = z.looseObject({
	Name: z.string(),
	Region: z.string(),
	ReplicationRegions: z.array(z.unknown()).optional(),
	ZoneTier: z.number().int().optional(),
	StorageZoneType: z.number().int().optional(),
});
export type StorageZoneAddDetails = z.infer<typeof StorageZoneAddDetailsSchema>;

// StorageZoneSettingsModel (core spec)
export const StorageZoneSettingsDetailsSchema = z.looseObject({
	ReplicationZones: z.array(z.unknown()).optional(),
	OriginUrl: z.string().optional(),
	Custom404FilePath: z.string().optional(),
	Rewrite404To200: z.boolean().optional(),
});
export type StorageZoneSettingsDetails = z.infer<
	typeof StorageZoneSettingsDetailsSchema
>;

// AddDnsRecordModel (core spec)
export const DnsRecordDetailsSchema = z.looseObject({
	Type: z.number().int().optional(),
	Ttl: z.number().optional(),
	Value: z.string().optional(),
	Name: z.string().optional(),
	Weight: z.number().optional(),
	Priority: z.number().optional(),
	Flags: z.number().optional(),
	Tag: z.string().optional(),
	Port: z.number().optional(),
	PullZoneId: z.number().optional(),
	ScriptId: z.number().optional(),
	Accelerated: z.boolean().optional(),
	MonitorType: z.number().int().optional(),
	GeolocationLatitude: z.number().optional(),
	GeolocationLongitude: z.number().optional(),
	LatencyZone: z.string().optional(),
	SmartRoutingType: z.number().int().optional(),
	Disabled: z.boolean().optional(),
	EnviromentalVariables: z.array(z.unknown()).optional(),
	Comment: z.string().optional(),
	AutoSslIssuance: z.boolean().optional(),
});
export type DnsRecordDetails = z.infer<typeof DnsRecordDetailsSchema>;

// ShieldZoneRequest (shield spec)
export const ShieldZoneRequestDetailsSchema = z.looseObject({
	shieldZoneId: z.number().optional(),
	premiumPlan: z.boolean().optional(),
	planType: z.number().int().optional(),
	learningMode: z.boolean().optional(),
	learningModeUntil: z.string().optional(),
	wafEnabled: z.boolean().optional(),
	wafExecutionMode: z.number().int().optional(),
	wafDisabledRules: z.array(z.unknown()).optional(),
	wafLogOnlyRules: z.array(z.unknown()).optional(),
	wafCustomRuleOrder: z.array(z.unknown()).optional(),
	wafRequestHeaderLoggingEnabled: z.boolean().optional(),
	requestBodyLoggingEnabled: z.boolean().optional(),
	wafRequestIgnoredHeaders: z.array(z.unknown()).optional(),
	wafRealtimeThreatIntelligenceEnabled: z.boolean().optional(),
	wafProfileId: z.number().optional(),
	wafEngineConfig: z.array(z.unknown()).optional(),
	wafRequestBodyLimitAction: z.number().int().optional(),
	wafResponseBodyLimitAction: z.number().int().optional(),
	dDoSShieldSensitivity: z.number().int().optional(),
	dDoSChallengeWindow: z.number().optional(),
	whitelabelResponsePages: z.boolean().optional(),
});
export type ShieldZoneRequestDetails = z.infer<
	typeof ShieldZoneRequestDetailsSchema
>;

// CreateWafRateLimitRuleModel (shield spec)
export const RateLimitRuleConfigDetailsSchema = z.looseObject({
	actionType: z.number().int().optional(),
	variableTypes: z.looseObject({}).optional(),
	operatorType: z.number().int().optional(),
	severityType: z.number().int().optional(),
	transformationTypes: z.array(z.unknown()).optional(),
	value: z.string().optional(),
	isNegated: z.boolean().optional(),
	isRegexVariable: z.boolean().optional(),
	requestCount: z.number().optional(),
	counterKeyType: z.number().int().optional(),
	timeframe: z.number().int().optional(),
	blockTime: z.number().int().optional(),
	chainedRuleConditions: z.array(z.unknown()).optional(),
});
export type RateLimitRuleConfigDetails = z.infer<
	typeof RateLimitRuleConfigDetailsSchema
>;
