import type { EndpointRiskLevel } from 'corsair/core';

export type WixMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

export type WixRoute = {
	key: string;
	group: string;
	name: string;
	method: WixMethod;
	path: string;
	/** Oss spec op code (corsair.dev/oss/wix) for traceability. */
	specCode: string;
	description: string;
	pathParams?: readonly string[];
	queryParams?: readonly string[];
	/**
	 * True when the endpoint takes Wix query-language options (filter, sort,
	 * paging, fields, fieldsets, search) wrapped as `{ query: {...} }` in the
	 * POST body. Enables limit/offset pagination support.
	 */
	queryBody?: boolean;
	searchBody?: boolean;
	/**
	 * True when the endpoint speaks GraphQL: the POST body must be
	 * `{ query: <GraphQL document string>, variables: {...} }`, not the
	 * Wix `{ query: {...} }` options envelope.
	 */
	graphql?: boolean;
	riskLevel: EndpointRiskLevel;
	irreversible?: boolean;
};

export const wixRoutes: WixRoute[] = [
	// ── contacts ──────────────────────────────────────────────────────────
	{
		key: 'queryContacts',
		group: 'contacts',
		name: 'query',
		method: 'POST',
		path: '/contacts/v4/contacts/query',
		specCode: 'WIX_QUERY_CONTACTS',
		description:
			'Tool to retrieve up to 1,000 Wix contacts with advanced filtering, sorting, and pagination. Use when you need to search for specific contacts or retrieve contacts with custom field selections.',
		queryBody: true,
		riskLevel: 'read',
	},
	{
		key: 'listContacts',
		group: 'contacts',
		name: 'list',
		method: 'GET',
		path: '/contacts/v4/contacts',
		specCode: 'WIX_LIST_V4_CONTACTS',
		description:
			'Tool to retrieve a list of up to 1,000 contacts per request from Wix. Use when you need to fetch contact information with support for pagination and field filtering.',
		queryParams: ['limit', 'offset', 'fieldsets', 'fields'],
		riskLevel: 'read',
	},
	{
		key: 'bulkUpdateContacts',
		group: 'contacts',
		name: 'bulkUpdate',
		method: 'POST',
		path: '/contacts/v4/bulk/contacts/update',
		specCode: 'WIX_UPDATE_CONTACTS_BULK',
		description:
			'Tool to bulk update multiple contacts with specified field values. Use when you need to update the same field(s) across multiple contacts matching a filter or search criteria. Only fields specified in fieldMask.paths will be updated.',
		riskLevel: 'write',
	},
	{
		key: 'addContactLabels',
		group: 'contacts',
		name: 'addLabels',
		method: 'POST',
		path: '/contacts/v4/contacts/{contactId}/labels',
		specCode: 'WIX_CREATE_CONTACTS_LABELS',
		description:
			"Tool to add labels to a Wix contact using the Labels API. Use when you need to categorize or tag contacts with specific labels like 'contacts.customers' or 'contacts.contacted-me'.",
		pathParams: ['contactId'],
		riskLevel: 'write',
	},
	{
		key: 'unlabelContact',
		group: 'contacts',
		name: 'unlabel',
		method: 'DELETE',
		path: '/contacts/v4/contacts/{contactId}/labels',
		specCode: 'WIX_DELETE_CONTACTS_LA',
		description:
			'Tool to remove labels from a contact in the Wix CRM system. Use when you need to unlabel a contact by removing specific label keys. This triggers a Contact Updated event in the Wix system.',
		pathParams: ['contactId'],
		queryParams: ['labelKeys'],
		riskLevel: 'write',
	},
	{
		key: 'listContactsFacets',
		group: 'contacts',
		name: 'listFacets',
		method: 'GET',
		path: '/contacts/v4/contacts/facets',
		specCode: 'WIX_LIST_CONTACTS_FACETS',
		description:
			"Tool to list facets from the site's Contact List. Facets include labels, subscription statuses (email and SMS), and membership statuses. Use when you need to retrieve available contact categorization options with their counts.",
		riskLevel: 'read',
	},
	{
		key: 'queryContactsFacets',
		group: 'contacts',
		name: 'queryFacets',
		method: 'POST',
		path: '/contacts/v4/contacts/facets/query',
		specCode: 'WIX_QUERY_FACETS_QUERY',
		description:
			"Tool to retrieve facets from the site's contact list by filter. Facets include labels and subscription statuses with aggregated contact counts. Use when you need to get contact segmentation data.",
		queryBody: true,
		riskLevel: 'read',
	},
	// ── stores ────────────────────────────────────────────────────────────
	{
		key: 'searchProducts',
		group: 'stores',
		name: 'searchProducts',
		method: 'POST',
		path: '/stores/v3/products/search',
		specCode: 'WIX_SEARCH_PRODUCTS',
		description:
			'Tool to search products in the Wix store catalog using text search, filters, and sorting. Returns up to 100 products per request with cursor-based pagination. Use when you need to find specific products or retrieve products matching certain criteria.',
		searchBody: true,
		riskLevel: 'read',
	},
	{
		key: 'queryInventoryItems',
		group: 'stores',
		name: 'queryInventory',
		method: 'POST',
		path: '/stores/v3/inventory-items/query',
		specCode: 'WIX_QUERY_INVENTORY',
		description:
			'Tool to retrieve a list of up to 1000 inventory items with optional paging, filtering, and sorting. Manages inventory per variant including stock quantities, availability status, and preorder information. Use when you need to fetch inventory data from a Wix Stores Catalog V3 site.',
		queryBody: true,
		riskLevel: 'read',
	},
	{
		key: 'bulkDeleteProducts',
		group: 'stores',
		name: 'bulkDeleteProducts',
		method: 'POST',
		path: '/stores/v3/products/bulk/delete',
		specCode: 'WIX_DELETE_PRODUCTS',
		description:
			'Tool to bulk delete products from the Wix Stores catalog. Use when you need to permanently remove multiple products by their IDs.',
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'bulkDeleteInventoryItems',
		group: 'stores',
		name: 'bulkDeleteInventoryItems',
		method: 'POST',
		path: '/stores/v3/inventory-items/bulk/delete',
		specCode: 'WIX_DELETE_INVENTORY_ITEMS_BULK',
		description:
			'Tool to bulk delete inventory items from the Wix Stores catalog. Accepts non-existent IDs without error. Use when you need to remove multiple inventory items at once.',
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'bulkDeleteBrands',
		group: 'stores',
		name: 'bulkDeleteBrands',
		method: 'POST',
		path: '/stores/v3/brands/bulk/delete',
		specCode: 'WIX_DELETE_BRANDS_BULK',
		description:
			"Tool to delete multiple brands from the Wix Stores catalog. When a brand is deleted, it's automatically removed from all products that reference it. Use when you need to remove multiple brands at once.",
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'bulkGetOrCreateBrands',
		group: 'stores',
		name: 'bulkGetOrCreateBrands',
		method: 'POST',
		path: '/stores/v3/brands/bulk/get-or-create',
		specCode: 'WIX_GET_OR_CREATE_BRANDS_BULK',
		description:
			"Tool to bulk retrieve or create brands in Wix Stores catalog. Retrieves multiple brands by name, or creates them if they don't exist. Use when you need to ensure specific brands exist in the catalog.",
		riskLevel: 'write',
	},
	{
		key: 'bulkUpdateProductsByFilter',
		group: 'stores',
		name: 'bulkUpdateProductsByFilter',
		method: 'POST',
		path: '/stores/v3/products/bulk/update-by-filter',
		specCode: 'WIX_UPDATE_PRODUCTS_BY_FILTER',
		description:
			'Tool to bulk update multiple products matching filter criteria in Wix Stores. Use when you need to update the same field(s) across multiple products matching specific conditions. Cannot update slug, options, modifiers, or variantsInfo fields.',
		riskLevel: 'write',
	},
	{
		key: 'bulkUpdateInventoryItemsByFilter',
		group: 'stores',
		name: 'bulkUpdateInventoryItemsByFilter',
		method: 'POST',
		path: '/stores/v3/inventory-items/bulk/update-by-filter',
		specCode: 'WIX_UPDATE_INVENTORY_ITEMS_BY_FILTER',
		description:
			'Tool to bulk update inventory items by filter criteria. Updates multiple inventory items matching the specified filter (e.g., by productId). Use when you need to change inventory tracking settings, stock status, or quantities for multiple items at once.',
		riskLevel: 'write',
	},
	{
		key: 'bulkUpdateCustomizations',
		group: 'stores',
		name: 'bulkUpdateCustomizations',
		method: 'POST',
		path: '/stores/v3/customizations/bulk/update',
		specCode: 'WIX_UPDATE_BULK_CUSTOMIZATIONS',
		description:
			'Tool to bulk update multiple customizations in Wix Stores Catalog V3. Use when you need to update properties of existing customizations such as name, type, choices, or settings. Each update requires the current revision number to prevent conflicts.',
		riskLevel: 'write',
	},
	{
		key: 'bulkCreateProductsWithInventory',
		group: 'stores',
		name: 'bulkCreateProductsWithInventory',
		method: 'POST',
		path: '/stores/v3/products/bulk/create-with-inventory',
		specCode: 'WIX_CREATE_PRODUCTS_WITH_INVENTORY_BULK_CREATE',
		description:
			'Tool to bulk create products with inventory in Wix. Use when you need to create multiple products with pricing and stock information in a single request. Supports up to 100 products per request. Physical products require physical_properties.',
		riskLevel: 'write',
	},
	{
		key: 'bulkRemoveInfoSectionsByFilter',
		group: 'stores',
		name: 'bulkRemoveInfoSectionsByFilter',
		method: 'POST',
		path: '/stores/v3/products/bulk/remove-info-sections-by-filter',
		specCode: 'WIX_REMOVE_INFO_SECTIONS_FROM_PRODUCTS_BY_FILTER',
		description:
			'Tool to bulk remove info sections from products matching a filter expression. Use when you need to detach information sections from multiple products based on specific criteria like visibility status, creation date, or other product attributes.',
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'deleteCustomization',
		group: 'stores',
		name: 'deleteCustomization',
		method: 'DELETE',
		path: '/stores/v3/customizations/{customizationId}',
		specCode: 'WIX_DELETE_CUSTOMIZATION',
		description:
			'Tool to delete a customization from the Wix Stores catalog. Use when you need to permanently remove a customization option by its ID.',
		pathParams: ['customizationId'],
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'deleteInfoSection',
		group: 'stores',
		name: 'deleteInfoSection',
		method: 'DELETE',
		path: '/stores/v3/info-sections/{infoSectionId}',
		specCode: 'WIX_DELETE_INFO_SECTION',
		description:
			'Tool to delete an info section from the Wix Stores catalog. Use when you need to permanently remove a specific info section by its ID.',
		pathParams: ['infoSectionId'],
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'deleteProductOptions',
		group: 'stores',
		name: 'deleteProductOptions',
		method: 'DELETE',
		path: '/stores/v3/products/{productId}/options',
		specCode: 'WIX_DELETE_PRODUCT_OPTIONS',
		description:
			'Tool to delete all options from a Wix product. Use when you need to remove all product options (like Color, Size) and reset the product to a single default variant. Only works when variant management is disabled.',
		pathParams: ['productId'],
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'setCustomizationChoices',
		group: 'stores',
		name: 'setCustomizationChoices',
		method: 'POST',
		path: '/stores/v3/customizations/{customizationId}/choices/set',
		specCode: 'WIX_SET_CUSTOMIZATION_CHOICES',
		description:
			'Tool to set choices for a customization in Wix stores catalog. Use when you need to replace all existing choices with a new set of choices for a customization. This operation requires a valid GUID customization ID and at least one choice with a name.',
		pathParams: ['customizationId'],
		riskLevel: 'write',
	},
	{
		key: 'updateInventoryVariants',
		group: 'stores',
		name: 'updateInventoryVariants',
		method: 'POST',
		path: '/stores/v3/inventory-items/bulk/update-variants',
		specCode: 'WIX_UPDATE_INVENTORY_VARIANTS',
		description:
			'Tool to update product inventory including quantity, stock status, and tracking settings per variant. Use when you need to modify inventory levels or stock configuration. The revision field must match the current value to prevent conflicts.',
		riskLevel: 'write',
	},
	{
		key: 'getCollectionBySlug',
		group: 'stores',
		name: 'getCollectionBySlug',
		method: 'GET',
		path: '/stores/v1/collections/slug/{slug}',
		specCode: 'WIX_GET_COLLECTION_BY_SLUG',
		description:
			"Tool to retrieve a Wix Stores collection by its slug. Use when you need to fetch collection details using the collection's URL-friendly identifier instead of its ID.",
		pathParams: ['slug'],
		riskLevel: 'read',
	},
	{
		key: 'listCurrencies',
		group: 'stores',
		name: 'listCurrencies',
		method: 'GET',
		path: '/currency-converter/v1/currencies',
		specCode: 'WIX_LIST_CURRENCIES',
		description:
			'Tool to retrieve the list of available currencies from Wix Currency Converter. Use when you need to get all supported currencies with their ISO codes and symbols.',
		riskLevel: 'read',
	},
	{
		key: 'queryCoupons',
		group: 'stores',
		name: 'queryCoupons',
		method: 'POST',
		path: '/coupons/v1/coupons/query',
		specCode: 'WIX_QUERY_COUPONS',
		description:
			'Tool to retrieve a list of up to 100 coupons with optional paging, filtering, and sorting. Use when you need to fetch coupons from a Wix store.',
		queryBody: true,
		riskLevel: 'read',
	},
	{
		key: 'deleteBackInStockNotification',
		group: 'stores',
		name: 'deleteBackInStockNotification',
		method: 'DELETE',
		path: '/ecom/v1/back-in-stock-notifications/{notificationId}',
		specCode: 'WIX_DELETE_BACK_IN_STOCK_NOTIFICATION',
		description:
			'Tool to delete a back in stock notification request from Wix e-commerce. Use when you need to remove a customer request to be notified when a product comes back in stock.',
		pathParams: ['notificationId'],
		riskLevel: 'destructive',
		irreversible: true,
	},
	// ── orders (e-commerce) ───────────────────────────────────────────────
	{
		key: 'queryEcomOrders',
		group: 'orders',
		name: 'query',
		method: 'POST',
		path: '/ecom/v1/orders/query',
		specCode: 'WIX_QUERY_E_COMMERCE_ORDERS',
		description:
			"Tool to retrieve e-commerce orders with advanced filtering, sorting, and pagination. Use when you need to search for specific orders or retrieve order lists. Default behavior excludes orders with status 'INITIALIZED'.",
		queryBody: true,
		riskLevel: 'read',
	},
	{
		key: 'bulkUpdateOrders',
		group: 'orders',
		name: 'bulkUpdate',
		method: 'POST',
		path: '/ecom/v1/bulk/orders/update',
		specCode: 'WIX_UPDATE_ORDERS_BULK',
		description:
			'Tool to bulk update properties of up to 100 e-commerce orders. Use when you need to update order fields like archived status, buyer information, billing/shipping addresses, or custom fields. To remove a field, pass null; note that buyerInfo and contactDetails cannot be removed.',
		riskLevel: 'write',
	},
	{
		key: 'bulkUpdateOrderTags',
		group: 'orders',
		name: 'bulkUpdateTags',
		method: 'POST',
		path: '/ecom/v1/orders/bulk/update-tags',
		specCode: 'WIX_UPDATE_ORDERS_UPDATE_TAGS',
		description:
			'Tool to synchronously update tags on multiple orders by list of order IDs. Use when you need to add or remove tags from multiple orders at once. If a tag appears in both assignTags and unassignTags, it will be assigned.',
		riskLevel: 'write',
	},
	{
		key: 'removeTipFromOrder',
		group: 'orders',
		name: 'removeTip',
		method: 'POST',
		path: '/ecom/v1/orders/{orderId}/remove-tip',
		specCode: 'WIX_REMOVE_TIP_FROM_ORDER',
		description:
			'Tool to remove a tip from an existing eCommerce order. Use when you need to remove tip charges that were previously added to an order.',
		pathParams: ['orderId'],
		riskLevel: 'write',
	},
	{
		key: 'bulkDeleteAbandonedCheckouts',
		group: 'orders',
		name: 'bulkDeleteAbandonedCheckouts',
		method: 'POST',
		path: '/ecom/v1/abandoned-checkouts/bulk/delete',
		specCode: 'WIX_DELETE_ABANDONED_CHECKOUTS_BULK',
		description:
			'Tool to bulk delete abandoned checkouts from Wix e-commerce. Use when you need to remove multiple abandoned checkouts by their IDs.',
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'listInvoicesByOrderIds',
		group: 'orders',
		name: 'listInvoicesByOrderIds',
		method: 'POST',
		path: '/ecom/v1/invoices/list-by-ids',
		specCode: 'WIX_LIST_INVOICES_LIST_BY_IDS',
		description:
			'Tool to retrieve invoice IDs and external app IDs for multiple orders. Use when you need to get invoice information associated with one or more Wix eCommerce orders.',
		riskLevel: 'read',
	},
	// ── bookings ──────────────────────────────────────────────────────────
	{
		key: 'queryBookingsCategories',
		group: 'bookings',
		name: 'queryCategories',
		method: 'POST',
		path: '/bookings/v1/categories/query',
		specCode: 'WIX_QUERY_CATEGORIES',
		description:
			'Tool to retrieve bookings service categories with optional filtering, sorting, and pagination. Use when you need to fetch categories that organize booking services in Wix Bookings.',
		queryBody: true,
		riskLevel: 'read',
	},
	{
		key: 'deleteBookingsService',
		group: 'bookings',
		name: 'deleteService',
		method: 'DELETE',
		path: '/bookings/v1/services/{serviceId}',
		specCode: 'WIX_DELETE_SERVICE',
		description:
			'Tool to delete a service from Wix Bookings. Use when you need to remove a single service by its ID. Triggers a Service Deleted event upon success.',
		pathParams: ['serviceId'],
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'bulkDeleteBookingsServices',
		group: 'bookings',
		name: 'bulkDeleteServices',
		method: 'POST',
		path: '/bookings/v1/services/bulk/delete',
		specCode: 'WIX_DELETE_SERVICES_IN_BULK',
		description:
			'Tool to bulk delete services from Wix Bookings. Use when you need to remove multiple services at once by providing their IDs.',
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'bulkDeleteBookingsServicesByFilter',
		group: 'bookings',
		name: 'bulkDeleteServicesByFilter',
		method: 'POST',
		path: '/bookings/v1/services/bulk/delete-by-filter',
		specCode: 'WIX_DELETE_SERVICES_BY_FILTER',
		description:
			'Tool to bulk delete booking services by filter criteria. The operation succeeds even if individual services can be deleted, with failure information returned in bulkActionMetadata. Triggers Service Deleted webhook for each successfully deleted service.',
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'deleteBookingsAddOnGroup',
		group: 'bookings',
		name: 'deleteAddOnGroup',
		method: 'DELETE',
		path: '/bookings/v1/services/{serviceId}/add-on-groups/{addOnGroupId}',
		specCode: 'WIX_DELETE_ADD_ON_GROUP',
		description:
			'Tool to delete an add-on group from a Wix Bookings service. Use when you need to remove an add-on group from a specific service by providing the service ID and add-on group ID.',
		pathParams: ['serviceId', 'addOnGroupId'],
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'queryExtendedBookings',
		group: 'bookings',
		name: 'queryExtendedBookings',
		method: 'POST',
		path: '/_api/bookings-reader/v2/extended-bookings/query',
		specCode: 'WIX_QUERY_EXTENDED_BOOKINGS',
		description:
			'Tool to retrieve up to 100 extended bookings with advanced filtering, sorting, and pagination. Use when you need to search for specific bookings with attendance details and customer action permissions. Default behavior returns 50 bookings sorted by id in ascending order.',
		queryBody: true,
		riskLevel: 'read',
	},
	{
		key: 'countExtendedBookings',
		group: 'bookings',
		name: 'countExtendedBookings',
		method: 'POST',
		path: '/_api/bookings-reader/v2/extended-bookings/count',
		specCode: 'WIX_COUNT_EXTENDED_BOOKINGS',
		description:
			'Tool to count extended bookings matching specified filter criteria. Use when you need to get the total number of bookings without retrieving the full booking data. Note: unlike query endpoints, the filter is sent at the top level of the body, not wrapped in a query envelope.',
		riskLevel: 'read',
	},
	{
		key: 'listBookingsSessions',
		group: 'bookings',
		name: 'listSessions',
		method: 'GET',
		path: '/bookings/v1/sessions',
		specCode: 'WIX_LIST_SESSIONS',
		description:
			'Tool to retrieve calendar sessions from Wix Bookings with filtering, sorting, and pagination. Use when you need to list booking sessions, event instances, or availability slots. Note: This endpoint is deprecated and may be replaced with newer Calendar V3 APIs.',
		queryParams: ['limit', 'offset'],
		riskLevel: 'read',
	},
	{
		key: 'updateStaffMemberTagsByFilter',
		group: 'bookings',
		name: 'updateStaffMemberTagsByFilter',
		method: 'POST',
		path: '/bookings/v1/staff-members/bulk/update-tags-by-filter',
		specCode: 'WIX_UPDATE_STAFF_MEMBER_TAGS_BY_FILTER',
		description:
			'Tool to bulk update tags on Wix Bookings staff members by filter criteria. Use when you need to add or remove tags from multiple staff members matching specific conditions. If a tag appears in both assign and unassign, it will be assigned.',
		riskLevel: 'write',
	},
	// ── members ───────────────────────────────────────────────────────────
	{
		key: 'getMember',
		group: 'members',
		name: 'get',
		method: 'GET',
		path: '/members/v1/members/{memberId}',
		specCode: 'WIX_GET_MEMBER',
		description:
			'Tool to retrieve a member by ID from Wix Members. Use when you need to fetch detailed information about a specific member. Note: Private members (default privacy status) are not returned for site visitor or member calls.',
		pathParams: ['memberId'],
		riskLevel: 'read',
	},
	{
		key: 'getMemberPrivacySettings',
		group: 'members',
		name: 'getPrivacySettings',
		method: 'GET',
		path: '/members/v1/site/privacy-settings',
		specCode: 'WIX_GET_MEMBER_PRIVACY_SETTINGS',
		description:
			'Tool to retrieve member privacy settings for a Wix site. Use when you need to check what privacy settings are currently configured, including whether members can make their profiles public.',
		riskLevel: 'read',
	},
	{
		key: 'getMembersCustomFieldApplications',
		group: 'members',
		name: 'getMembersCustomFieldApplications',
		method: 'POST',
		path: '/members/v1/members/custom-fields/applications',
		specCode: 'WIX_GET_MEMBERS_CUSTOM_FIELD_APPLICATIONS',
		description:
			'Tool to retrieve custom field applications for specified members. Use when you need to check which custom field applications apply to specific members.',
		riskLevel: 'read',
	},
	{
		key: 'getRolesCustomFieldApplications',
		group: 'members',
		name: 'getRolesCustomFieldApplications',
		method: 'POST',
		path: '/members/v1/roles/custom-fields/applications',
		specCode: 'WIX_GET_ROLES_CUSTOM_FIELD_APPLICATIONS',
		description:
			'Tool to retrieve custom field applications for specified roles. Use when you need to check which custom field applications apply to specific member roles.',
		riskLevel: 'read',
	},
	{
		key: 'getRolesInfo',
		group: 'members',
		name: 'getRolesInfo',
		method: 'GET',
		path: '/members/v1/roles',
		specCode: 'WIX_GET_ROLES_INFO',
		description:
			'Tool to retrieve all available roles in the requesting Wix account, including predefined and custom roles. Use when you need to list all roles configured for the account.',
		riskLevel: 'read',
	},
	{
		key: 'listMembersCustomFields',
		group: 'members',
		name: 'listCustomFields',
		method: 'GET',
		path: '/members/v1/custom-fields',
		specCode: 'WIX_LIST_CUSTOM_FIELDS',
		description:
			'Tool to retrieve a list of custom fields and fields provided by the Members Area. Use when you need to fetch available custom field definitions for member profiles. Fields are ordered by section and creation date.',
		queryParams: ['limit', 'offset'],
		riskLevel: 'read',
	},
	{
		key: 'listMemberFollowing',
		group: 'members',
		name: 'listFollowing',
		method: 'GET',
		path: '/members/v1/members/{memberId}/following',
		specCode: 'WIX_LIST_MEMBER_FOLLOWING',
		description:
			'Tool to retrieve the list of members followed by a given member in Wix Members. Use when you need to see which members a specific member is following. Note: This API is in Developer Preview and may be subject to change.',
		pathParams: ['memberId'],
		queryParams: ['limit', 'offset'],
		riskLevel: 'read',
	},
	{
		key: 'listMyMemberFollowers',
		group: 'members',
		name: 'listMyFollowers',
		method: 'GET',
		path: '/members/v1/members/current/followers',
		specCode: 'WIX_LIST_MY_MEMBER_FOLLOWERS',
		description:
			'Tool to retrieve the list of members who are following the current authenticated member in Wix Members. Use when you need to see which members follow the current user.',
		queryParams: ['limit', 'offset'],
		riskLevel: 'read',
	},
	{
		key: 'registerMemberV2',
		group: 'members',
		name: 'register',
		method: 'POST',
		path: '/_api/iam/authentication/v2/register',
		specCode: 'WIX_REGISTER_V2',
		description:
			'Tool to register a new member account on Wix site. Use when you need to create a new member with email and password authentication. Returns a session token that can be used to obtain access and refresh tokens.',
		riskLevel: 'write',
	},
	{
		key: 'logoutMember',
		group: 'members',
		name: 'logout',
		method: 'POST',
		path: '/members/v1/members/logout',
		specCode: 'WIX_LOGOUT',
		description:
			"Tool to terminate a member's session and clear authentication cookies. Use when you need to log out a user from their Wix session. When postLogoutRedirectUri is provided, returns a 302 redirect response.",
		riskLevel: 'write',
	},
	{
		key: 'sendMemberRecoveryEmail',
		group: 'members',
		name: 'sendRecoveryEmail',
		method: 'POST',
		path: '/members/v1/members/send-recovery-email',
		specCode: 'WIX_SEND_RECOVERY_EMAIL',
		description:
			'Tool to send a password recovery email to a Wix member with a link to reset their password. Use when a member needs to reset their password. The site must be published for this to work. Site owners will reset their Wix account password instead of site-specific password.',
		riskLevel: 'write',
	},
	// ── sites ─────────────────────────────────────────────────────────────
	{
		key: 'getSiteProperties',
		group: 'sites',
		name: 'getProperties',
		method: 'GET',
		path: '/site-properties/v4/properties',
		specCode: 'WIX_GET_SITE_PROPERTIES',
		description:
			"Tool to retrieve current snapshot of a site's properties including business profile, contact information, and business schedule. Use when you need to fetch site-level business information, contact details, or operating hours.",
		riskLevel: 'read',
	},
	{
		key: 'updateBusinessContact',
		group: 'sites',
		name: 'updateBusinessContact',
		method: 'POST',
		path: '/site-properties/v4/properties/business-contact',
		specCode: 'WIX_UPDATE_BUSINESS_CONTACT',
		description:
			"Tool to update a site's business contact information including email, phone, fax, and address. Use when you need to modify the public business contact details displayed on a Wix site. Requires Manage Business Contact permission scope.",
		riskLevel: 'write',
	},
	{
		key: 'updateBusinessProfile',
		group: 'sites',
		name: 'updateBusinessProfile',
		method: 'POST',
		path: '/site-properties/v4/properties/business-profile',
		specCode: 'WIX_UPDATE_BUSINESS_PROFILE',
		description:
			"Tool to update a site's business profile including display name, description, logo, and business name. Use when you need to modify public business information. Only fields specified in the fields.paths array are updated.",
		riskLevel: 'write',
	},
	{
		key: 'updateBusinessSchedule',
		group: 'sites',
		name: 'updateBusinessSchedule',
		method: 'POST',
		path: '/site-properties/v4/properties/business-schedule',
		specCode: 'WIX_UPDATE_BUSINESS_SCHEDULE',
		description:
			"Tool to update a site's business schedule including regular operating hours and special exceptions. Use when you need to set or modify business hours, add holiday closures, or define special event hours. The update replaces the entire schedule, so include all desired periods in each request.",
		riskLevel: 'write',
	},
	{
		key: 'updateLocaleSettings',
		group: 'sites',
		name: 'updateLocaleSettings',
		method: 'POST',
		path: '/multilingual/v1/locale-settings',
		specCode: 'WIX_UPDATE_LOCALE_SETTINGS',
		description:
			"Tool to update a Wix site's locale configuration settings including auto-redirect behavior. Use when you need to modify locale settings such as enabling or disabling automatic visitor redirection based on language preferences. Note: This action cannot update a site's multilingual mode; use the Set Multilingual Mode action for that.",
		riskLevel: 'write',
	},
	{
		key: 'checkDomainAvailability',
		group: 'sites',
		name: 'checkDomainAvailability',
		method: 'POST',
		path: '/domains/v1/availability/check',
		specCode: 'WIX_CHECK_DOMAIN_AVAILABILITY',
		description:
			'Tool to check if a domain name is available for purchase. Use when you need to verify domain availability before registration. Returns an availability object with a boolean indicating if the domain can be purchased.',
		riskLevel: 'read',
	},
	{
		key: 'getFolderBySite',
		group: 'sites',
		name: 'getFolderBySite',
		method: 'GET',
		path: '/site-folders/v2/folders/sites/{targetSiteId}',
		specCode: 'WIX_GET_FOLDER_BY_SITE',
		description:
			'Tool to retrieve folder information for a specific site by site ID. Use when you need to get the parent folder details of a site. Note: If the specified site is at root level, the returned folder object will be empty.',
		pathParams: ['targetSiteId'],
		riskLevel: 'read',
	},
	{
		key: 'querySiteFolders',
		group: 'sites',
		name: 'queryFolders',
		method: 'POST',
		path: '/site-folders/v2/folders/query',
		specCode: 'WIX_QUERY_FOLDERS',
		description:
			'Tool to retrieve a list of site folders with optional paging, filtering, and sorting. Use when you need to organize and manage Wix sites by folders in an account.',
		queryBody: true,
		riskLevel: 'read',
	},
	{
		key: 'queryLocations',
		group: 'sites',
		name: 'queryLocations',
		method: 'POST',
		path: '/business-locations/v2/locations/query',
		specCode: 'WIX_QUERY_LOCATIONS',
		description:
			'Tool to retrieve business locations with filtering, sorting, and pagination. Use when you need to search for specific locations or list all locations for a site.',
		queryBody: true,
		riskLevel: 'read',
	},
	{
		key: 'getSitePluginsPlacementStatus',
		group: 'sites',
		name: 'getSitePluginsPlacementStatus',
		method: 'GET',
		path: '/apps/v1/site-plugins/placement-status',
		specCode: 'WIX_GET_SITE_PLUGINS_PLACEMENT_STATUS',
		description:
			"Tool to get the placement status of your app's site plugins on the user's site. Use when you need to check whether your plugins are currently placed in slots on the user's site.",
		riskLevel: 'read',
	},
	// ── marketing ─────────────────────────────────────────────────────────
	{
		key: 'listEmailCampaigns',
		group: 'marketing',
		name: 'listCampaigns',
		method: 'GET',
		path: '/email-marketing/v1/campaigns',
		specCode: 'WIX_LIST_CAMPAIGNS',
		description:
			'Tool to retrieve a list of email marketing campaigns, ordered by date_updated in descending order. Use when you need to get campaigns from Wix Email Marketing with optional filtering by status, visibility, or distribution status.',
		queryParams: ['status', 'limit', 'offset'],
		riskLevel: 'read',
	},
	{
		key: 'getSenderDetails',
		group: 'marketing',
		name: 'getSenderDetails',
		method: 'GET',
		path: '/email-marketing/v1/senders/default',
		specCode: 'WIX_GET_SENDER_DETAILS',
		description:
			'Tool to retrieve sender details for email marketing campaigns. Use when you need to fetch the sender name and email address. Note: This endpoint is deprecated and has been superseded by the Get Default Sender Details endpoint.',
		riskLevel: 'read',
	},
	{
		key: 'deleteSenderDetails',
		group: 'marketing',
		name: 'deleteSenderDetails',
		method: 'DELETE',
		path: '/email-marketing/v1/senders/{senderId}',
		specCode: 'WIX_DELETE_SENDER_DETAILS',
		description:
			'Tool to delete sender details from Wix email marketing. Use when you need to remove a sender from the available senders list. Note: You cannot delete a default sender - you must first create a new sender and mark it as default before deleting the original.',
		pathParams: ['senderId'],
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'deleteSenderEmail',
		group: 'marketing',
		name: 'deleteSenderEmail',
		method: 'DELETE',
		path: '/email-marketing/v1/senders/emails/{emailId}',
		specCode: 'WIX_DELETE_SENDER_EMAIL',
		description:
			'Tool to delete a sender email from Wix Marketing. Use when you need to remove a specific sender email by its ID.',
		pathParams: ['emailId'],
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'updateReferralProgram',
		group: 'marketing',
		name: 'updateReferralProgram',
		method: 'PATCH',
		path: '/referral/v1/program',
		specCode: 'WIX_UPDATE_REFERRAL_PROGRAM',
		description:
			"Tool to update a site's referral program configuration including name, rewards, and email settings. Use when you need to modify an existing referral program. The revision field is required to prevent conflicting updates.",
		riskLevel: 'write',
	},
	{
		key: 'getCurrentMemberCoupons',
		group: 'marketing',
		name: 'getCurrentMemberCoupons',
		method: 'GET',
		path: '/loyalty/v1/current-member/coupons',
		specCode: 'WIX_GET_CURRENT_MEMBER_COUPONS',
		description:
			'Tool to retrieve loyalty coupons for the currently authenticated member. Use when you need to fetch loyalty program coupons for the logged-in member. Requires visitor or member authentication.',
		riskLevel: 'read',
	},
	{
		key: 'deleteLoyaltyCoupon',
		group: 'marketing',
		name: 'deleteLoyaltyCoupon',
		method: 'DELETE',
		path: '/loyalty-coupons/v1/coupons/{couponId}',
		specCode: 'WIX_DELETE_LOYALTY_COUPON',
		description:
			'Tool to delete a loyalty coupon from the Wix Loyalty Program. Note that deleting a loyalty coupon does not affect the functionality of the corresponding discount coupon itself. Use when you need to remove a loyalty coupon by its unique identifier.',
		pathParams: ['couponId'],
		queryParams: ['revision'],
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'enablePointsExpiration',
		group: 'marketing',
		name: 'enablePointsExpiration',
		method: 'POST',
		path: '/loyalty/v1/points-expiration/enable',
		specCode: 'WIX_CREATE_POINTS_EXPIRATION_ENABLE',
		description:
			'Tool to enable points expiration for a Wix loyalty program. Use when you need to activate the points expiration feature, which changes the pointsExpiration status to ENABLED.',
		riskLevel: 'write',
	},
	{
		key: 'queryLoyaltyCheckoutDiscounts',
		group: 'marketing',
		name: 'queryLoyaltyCheckoutDiscounts',
		method: 'POST',
		path: '/loyalty-checkout-exchange/v1/loyalty-checkout-discounts/query',
		specCode: 'WIX_QUERY_LOYALTY_CHECKOUT_DISCOUNTS',
		description:
			'Tool to retrieve loyalty checkout discounts with filtering, sorting, and pagination. Use when you need to query discounts applied at checkout using loyalty points.',
		queryBody: true,
		riskLevel: 'read',
	},
	// ── forms ─────────────────────────────────────────────────────────────
	{
		key: 'bulkDeleteFormSchemas',
		group: 'forms',
		name: 'bulkDeleteSchemas',
		method: 'POST',
		path: '/forms/v4/bulk/forms/delete',
		specCode: 'WIX_DELETE_FORMS',
		description:
			'Tool to bulk delete form schemas from Wix Forms. Use when you need to remove multiple forms by their IDs in a single operation.',
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'queryDeletedForms',
		group: 'forms',
		name: 'queryDeletedForms',
		method: 'POST',
		path: '/form-schema-service/v4/forms/trash-bin/query',
		specCode: 'WIX_QUERY_DELETED_FORMS',
		description:
			'Tool to retrieve deleted form schemas from the trash bin for a specified namespace. Use when you need to query forms that have been deleted but not permanently removed. Requires namespace filter.',
		queryBody: true,
		riskLevel: 'read',
	},
	{
		key: 'queryFormSubmissionsByNamespace',
		group: 'forms',
		name: 'querySubmissionsByNamespace',
		method: 'POST',
		path: '/forms/v4/submissions/namespace/query',
		specCode: 'WIX_QUERY_SUBMISSIONS_BY_NAMESPACE',
		description:
			'Tool to retrieve form submissions from a specified namespace with advanced filtering, sorting, and pagination. Use when you need to query submissions with specific criteria like status, date ranges, or visibility. Namespace filter is required using $eq operator.',
		queryBody: true,
		riskLevel: 'read',
	},
	{
		key: 'queryFormsFormSubmissions',
		group: 'forms',
		name: 'queryFormsSubmissions',
		method: 'POST',
		path: '/forms/v4/submissions/namespace/query',
		specCode: 'WIX_QUERY_FORMS_FORM_SUBMISSIONS',
		description:
			'Tool to retrieve form submissions from a specified namespace with optional pagination. Use when you need to query form submissions from Wix Forms or other form apps. The namespace filter is required.',
		queryBody: true,
		riskLevel: 'read',
	},
	{
		key: 'removeDeletedFields',
		group: 'forms',
		name: 'removeDeletedFields',
		method: 'POST',
		path: '/form-schema-service/v4/forms/fields/delete',
		specCode: 'WIX_REMOVE_DELETED_FIELDS',
		description:
			'Tool to permanently remove deleted fields from a Wix form schema. Use when you need to clean up deleted fields from a form.',
		riskLevel: 'destructive',
		irreversible: true,
	},
	// ── events ────────────────────────────────────────────────────────────
	{
		key: 'findEvent',
		group: 'events',
		name: 'find',
		method: 'GET',
		path: '/events/v1/events/{eventId}',
		specCode: 'WIX_FIND_EVENT',
		description:
			'Tool to find a Wix event by ID or slug. Use when you need to retrieve event details. Note: This endpoint is deprecated and will be replaced by Events V3 Get Event.',
		pathParams: ['eventId'],
		riskLevel: 'read',
	},
	{
		key: 'queryEventsGraphql',
		group: 'events',
		name: 'queryEventsGraphql',
		method: 'POST',
		path: '/graphql',
		specCode: 'WIX_QUERY_EVENTS_EVENTS',
		description:
			'Tool to query events using the deprecated eventsEvents GraphQL endpoint. Returns event items and pagination info. Note: This endpoint is deprecated and will be replaced with Events V3 Query Events endpoint.',
		graphql: true,
		riskLevel: 'read',
	},
	{
		key: 'bulkDeleteRsvpsByFilter',
		group: 'events',
		name: 'bulkDeleteRsvpsByFilter',
		method: 'POST',
		path: '/events/v1/rsvps/bulk/delete-by-filter',
		specCode: 'WIX_DELETE_RSVPS_BY_FILTER',
		description:
			'Tool to bulk delete event RSVPs by filter criteria. Use when you need to remove multiple RSVPs matching specific conditions. If no filter is provided, this may delete all RSVPs.',
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'bulkDeleteTicketDefinitions',
		group: 'events',
		name: 'bulkDeleteTicketDefinitions',
		method: 'POST',
		path: '/events/v1/tickets/definitions/bulk/delete-by-filter',
		specCode: 'WIX_DELETE_TICKET_DEFINITIONS_BULK',
		description:
			"Tool to bulk delete ticket definitions by filter criteria for Wix Events. Use when you need to delete multiple ticket definitions matching specific conditions. Requires 'Manage Ticket Definitions' permission.",
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'deleteTicketCheckIn',
		group: 'events',
		name: 'deleteTicketCheckIn',
		method: 'POST',
		path: '/events/v1/tickets/check-in/delete',
		specCode: 'WIX_DELETE_TICKET_CHECK_IN',
		description:
			'Tool to delete ticket check-in records for Wix Events. Use when you need to remove check-in status for one or more tickets at an event.',
		riskLevel: 'write',
	},
	{
		key: 'deleteTicketReservation',
		group: 'events',
		name: 'deleteTicketReservation',
		method: 'DELETE',
		path: '/events/v1/tickets/reservations/{reservationId}',
		specCode: 'WIX_DELETE_TICKET_RESERVATION',
		description:
			'Tool to delete a ticket reservation from Wix Events. Use when you need to remove a ticket reservation that is no longer needed or valid.',
		pathParams: ['reservationId'],
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'deleteScheduleItem',
		group: 'events',
		name: 'deleteScheduleItem',
		method: 'POST',
		path: '/events/v1/events/{eventId}/schedule-items/delete',
		specCode: 'WIX_DELETE_SCHEDULE_ITEM',
		description:
			"Tool to delete schedule items from a Wix event. Use when you need to remove one or more schedule items from an event's draft schedule.",
		pathParams: ['eventId'],
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'deleteScheduleBookmark',
		group: 'events',
		name: 'deleteScheduleBookmark',
		method: 'DELETE',
		path: '/events/v1/schedules/{scheduleId}/bookmarks/{bookmarkId}',
		specCode: 'WIX_DELETE_BOOKMARK',
		description:
			"Tool to remove a bookmark from a schedule item in Wix Events. Use when you need to delete a user's saved bookmark for a specific event schedule item.",
		pathParams: ['scheduleId', 'bookmarkId'],
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'discardDraftSchedule',
		group: 'events',
		name: 'discardDraft',
		method: 'POST',
		path: '/events/v1/events/{eventId}/schedule/discard-draft',
		specCode: 'WIX_DISCARD_DRAFT',
		description:
			"Tool to discard all changes to a draft schedule for a Wix event. Use when you need to revert all unsaved changes and restore the schedule to its published state. Requires 'Manage Events - all permissions' scope.",
		pathParams: ['eventId'],
		riskLevel: 'write',
	},
	{
		key: 'publishDraftSchedule',
		group: 'events',
		name: 'publishDraft',
		method: 'POST',
		path: '/events/v1/events/{eventId}/schedule/publish-draft',
		specCode: 'WIX_PUBLISH_DRAFT',
		description:
			'Tool to publish a draft schedule for a Wix event. Use when you need to make all draft changes live and visible to site visitors. Requires Manage Events - all permissions scope.',
		pathParams: ['eventId'],
		riskLevel: 'write',
	},
	{
		key: 'rescheduleDraftSchedule',
		group: 'events',
		name: 'rescheduleDraft',
		method: 'POST',
		path: '/events/v1/events/{eventId}/schedule/reschedule-draft',
		specCode: 'WIX_RESCHEDULE_DRAFT',
		description:
			'Tool to reschedule all draft schedule items for an event at once. Use when you need to adjust the time of multiple draft schedule items simultaneously by specifying a new time zone.',
		pathParams: ['eventId'],
		riskLevel: 'write',
	},
	{
		key: 'bulkUnassignEventsFromCategories',
		group: 'events',
		name: 'bulkUnassignFromCategories',
		method: 'POST',
		path: '/events/v1/categories/bulk/unassign-events',
		specCode: 'WIX_UNASSIGN_EVENTS_BULK',
		description:
			'Tool to unassign an event from multiple categories in Wix Events. Use when you need to remove an event from one or more categories by providing the event ID and category IDs.',
		riskLevel: 'write',
	},
	// ── restaurants ───────────────────────────────────────────────────────
	{
		key: 'deleteRestaurantMenu',
		group: 'restaurants',
		name: 'deleteMenu',
		method: 'DELETE',
		path: '/restaurants/v1/menus/{menuId}',
		specCode: 'WIX_DELETE_MENU',
		description:
			'Tool to delete a menu from Wix Restaurants. Use when you need to permanently remove a menu by its ID. The endpoint implements idempotent DELETE behavior.',
		pathParams: ['menuId'],
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'bulkDeleteMenuModifiers',
		group: 'restaurants',
		name: 'bulkDeleteModifiers',
		method: 'POST',
		path: '/restaurants/v1/menus/modifiers/bulk/delete',
		specCode: 'WIX_DELETE_MODIFIERS_BULK',
		description:
			'Tool to bulk delete item modifiers from Wix Restaurants Menus. Use when you need to remove multiple item modifiers at once by providing their IDs.',
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'bulkDeleteMenuVariants',
		group: 'restaurants',
		name: 'bulkDeleteVariants',
		method: 'POST',
		path: '/restaurants/v1/menus/variants/bulk/delete',
		specCode: 'WIX_DELETE_BULK_VARIANTS',
		description:
			'Tool to bulk delete item variants from Wix Restaurants menus. Use when you need to remove multiple menu item variants at once.',
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'listRestaurantCatalogs',
		group: 'restaurants',
		name: 'listCatalogs',
		method: 'GET',
		path: '/restaurants/v1/catalogs',
		specCode: 'WIX_LIST_CATALOGS',
		description:
			'Tool to retrieve a list of restaurant catalogs from Wix Restaurants. Use when you need to get all catalogs for a restaurant location. Note: This API is deprecated and has been replaced with the Menus API.',
		queryParams: ['limit', 'offset'],
		riskLevel: 'read',
	},
	{
		key: 'bulkDeleteNotificationRecipients',
		group: 'restaurants',
		name: 'bulkDeleteNotificationRecipients',
		method: 'POST',
		path: '/restaurants/v1/orders/recipients/bulk/delete',
		specCode: 'WIX_DELETE_RECIPIENTS_BULK',
		description:
			'Tool to bulk delete notification recipients for Wix Restaurants online orders. Use when you need to remove multiple recipients at once by providing their IDs.',
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'deleteServiceFeeRule',
		group: 'restaurants',
		name: 'deleteServiceFeeRule',
		method: 'DELETE',
		path: '/restaurants/v1/orders/fee-rules/{ruleId}',
		specCode: 'WIX_DELETE_RULE',
		description:
			'Tool to delete a service fee rule from Wix Restaurants Online Orders. Use when you need to remove a specific rule by its ID.',
		pathParams: ['ruleId'],
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'calculateFirstAvailableSlots',
		group: 'restaurants',
		name: 'calculateFirstAvailableSlots',
		method: 'POST',
		path: '/restaurants/v1/menus/calculate-first-available-slots',
		specCode: 'WIX_CALCULATE_FIRST_AVAILABLE_TIME_SLOTS_PER_MENU',
		description:
			'Tool to calculate and retrieve the first available time slot of each fulfillment type for each specified menu. Use when you need to check availability for restaurant operations. Note: Developer Preview status - API is subject to change.',
		riskLevel: 'read',
	},
	// ── billing (get-paid, tax, receipts) ─────────────────────────────────
	{
		key: 'bulkDeleteBillableItems',
		group: 'billing',
		name: 'bulkDeleteBillableItems',
		method: 'POST',
		path: '/billing/v1/billable-items/bulk/delete',
		specCode: 'WIX_DELETE_BILLABLE_ITEMS_BULK',
		description:
			'Tool to bulk delete billable items in Wix. Use when you need to remove multiple billable items at once by providing their IDs. This triggers a Billable Item Deleted event in the Wix system.',
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'bulkUpdateBillableItems',
		group: 'billing',
		name: 'bulkUpdateBillableItems',
		method: 'POST',
		path: '/billing/v1/billable-items/bulk/update',
		specCode: 'WIX_UPDATE_BILLABLE_ITEMS_BULK',
		description:
			'Tool to bulk update billable items in Wix. Use when you need to modify multiple billable items at once. Each item requires its ID, current revision number, and the fields to update.',
		riskLevel: 'write',
	},
	{
		key: 'createTaxRegion',
		group: 'billing',
		name: 'createTaxRegion',
		method: 'POST',
		path: '/tax/v1/regions',
		specCode: 'WIX_CREATE_TAX_REGION',
		description:
			'Tool to create a tax region in Wix using the Tax Regions API. Use when you need to define a location-specific tax treatment by country and subdivision with an associated tax calculator.',
		riskLevel: 'write',
	},
	{
		key: 'listDefaultTaxGroups',
		group: 'billing',
		name: 'listDefaultTaxGroups',
		method: 'GET',
		path: '/tax/v1/default-groups',
		specCode: 'WIX_LIST_DEFAULT_TAX_GROUPS',
		description:
			'Tool to retrieve the list of default tax groups for a Wix site. Use when you need to fetch the default tax groups that are inherited by apps installed on the site.',
		riskLevel: 'read',
	},
	{
		key: 'listDefaultTaxGroupsByAppIds',
		group: 'billing',
		name: 'listDefaultTaxGroupsByAppIds',
		method: 'POST',
		path: '/tax/v1/default-groups/list-by-app-ids',
		specCode: 'WIX_LIST_DEFAULT_TAX_GROUPS_BY_APP_IDS',
		description:
			'Tool to retrieve default tax groups for specific Wix apps by their app IDs. Use when you need to fetch predefined tax groups that are automatically assigned to products from specific apps.',
		riskLevel: 'read',
	},
	{
		key: 'listManualTaxMappings',
		group: 'billing',
		name: 'listManualTaxMappings',
		method: 'GET',
		path: '/tax/v1/manual-mappings',
		specCode: 'WIX_LIST_MANUAL_TAX_MAPPINGS',
		description:
			'Tool to retrieve up to 1,000 manual tax mappings from Wix. Use when you need to list custom tax rate configurations for specific tax group and region combinations. Results are sorted by createdDate in ascending order.',
		queryParams: ['limit', 'offset'],
		riskLevel: 'read',
	},
	{
		key: 'queryManualTaxMappings',
		group: 'billing',
		name: 'queryManualTaxMappings',
		method: 'POST',
		path: '/tax/v1/manual-mappings/query',
		specCode: 'WIX_QUERY_MANUAL_TAX_MAPPINGS',
		description:
			'Tool to retrieve a list of up to 100 manual tax mappings with optional paging, filtering, and sorting. Use when you need to query custom tax rate configurations for specific tax group and region combinations from a Wix store.',
		queryBody: true,
		riskLevel: 'read',
	},
	{
		key: 'queryTaxGroups',
		group: 'billing',
		name: 'queryTaxGroups',
		method: 'POST',
		path: '/tax/v1/groups/query',
		specCode: 'WIX_QUERY_TAX_GROUPS',
		description:
			'Tool to retrieve a list of up to 100 tax groups with optional paging, filtering, and sorting. Only returns tax groups created by the site, not default tax groups. Use when you need to fetch custom tax group configurations from a Wix site.',
		queryBody: true,
		riskLevel: 'read',
	},
	{
		key: 'deleteReceiptPreset',
		group: 'billing',
		name: 'deleteReceiptPreset',
		method: 'DELETE',
		path: '/receipts/v1/presets/{presetId}',
		specCode: 'WIX_DELETE_RECEIPT_PRESET',
		description:
			'Tool to permanently delete a receipt preset from Wix. Use when you need to remove a receipt preset by its ID. This triggers a Receipt Preset Deleted event in the Wix system.',
		pathParams: ['presetId'],
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'setDefaultReceiptPreset',
		group: 'billing',
		name: 'setDefaultReceiptPreset',
		method: 'POST',
		path: '/receipts/v1/presets/{presetId}/set-default',
		specCode: 'WIX_SET_DEFAULT_RECEIPT_PRESET',
		description:
			'Tool to set a receipt preset as the default in Wix. Use when you need to designate a specific receipt preset as the default for receipt generation.',
		pathParams: ['presetId'],
		riskLevel: 'write',
	},
	{
		key: 'updateReceiptPreset',
		group: 'billing',
		name: 'updateReceiptPreset',
		method: 'PATCH',
		path: '/receipts/v1/presets/{presetId}',
		specCode: 'WIX_UPDATE_RECEIPT_PRESET',
		description:
			'Tool to update a receipt preset in Wix. Use when you need to modify receipt preset settings including name, custom fields, display settings, or extended fields. Requires the current revision number to prevent conflicting changes. Triggers a Receipt Preset Updated event.',
		pathParams: ['presetId'],
		riskLevel: 'write',
	},
	// ── cms / data ────────────────────────────────────────────────────────
	{
		key: 'addSpecialPermissions',
		group: 'cms',
		name: 'addSpecialPermissions',
		method: 'POST',
		path: '/cms/v1/collections/{collectionId}/permissions/special',
		specCode: 'WIX_ADD_SPECIAL_PERMISSIONS',
		description:
			'Tool to add special permissions to a Wix data collection for a specific user or role. Use when you need to grant CRUD permissions (insert, update, remove, read) to a user or role for a specific collection.',
		pathParams: ['collectionId'],
		riskLevel: 'write',
	},
	{
		key: 'cancelBackgroundTask',
		group: 'cms',
		name: 'cancelTask',
		method: 'POST',
		path: '/cms/v1/background-tasks/{taskId}/cancel',
		specCode: 'WIX_CANCEL_TASK',
		description:
			'Tool to cancel a background task in Wix CMS. Use when you need to stop a running background task that is no longer needed.',
		pathParams: ['taskId'],
		riskLevel: 'write',
	},
	{
		key: 'deleteDataCollectionField',
		group: 'cms',
		name: 'deleteDataCollectionField',
		method: 'DELETE',
		path: '/cms/v1/collections/{collectionId}/fields/{fieldId}',
		specCode: 'WIX_DELETE_DATA_COLLECTION_FIELD',
		description:
			"Tool to delete a field from a Wix data collection. Use when you need to remove a field from a collection's structure, which also removes all associated values. The operation is idempotent and succeeds even if the collection or field doesn't exist.",
		pathParams: ['collectionId', 'fieldId'],
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'deleteUserDefinedFields',
		group: 'cms',
		name: 'deleteUserDefinedFields',
		method: 'POST',
		path: '/data-extensions/v1/schemas/{schemaId}/delete-fields',
		specCode: 'WIX_DELETE_USER_DEFINED_FIELDS',
		description:
			'Tool to delete user defined fields from a data extension schema in Wix. Use when you need to remove custom fields from a schema by providing the schema ID and field keys.',
		pathParams: ['schemaId'],
		riskLevel: 'destructive',
		irreversible: true,
	},
	// ── media ─────────────────────────────────────────────────────────────
	{
		key: 'generateFileUploadUrl',
		group: 'media',
		name: 'generateFileUploadUrl',
		method: 'POST',
		path: '/site-media/v1/files/generate-upload-url',
		specCode: 'WIX_GENERATE_FILE_UPLOAD_URL',
		description:
			'Tool to generate an upload URL for uploading files to Wix Media Manager. Use when you need to upload a file to Wix. Note: Files are not immediately available after upload and require processing time. For files larger than 10MB or poor network conditions, use Generate File Resumable Upload URL instead.',
		riskLevel: 'write',
	},
	{
		key: 'generateFilesDownloadUrl',
		group: 'media',
		name: 'generateFilesDownloadUrl',
		method: 'POST',
		path: '/site-media/v1/files/generate-download-url',
		specCode: 'WIX_GENERATE_FILES_DOWNLOAD_URL',
		description:
			'Tool to generate download URLs for files in Wix Media Manager. Use when you need to create a permanent download URL for one or multiple files (up to 1000). Returns a download URL for a compressed file containing all requested files.',
		riskLevel: 'read',
	},
	{
		key: 'importFileToMedia',
		group: 'media',
		name: 'importFile',
		method: 'POST',
		path: '/site-media/v1/files/import',
		specCode: 'WIX_IMPORT_FILE',
		description:
			'Tool to import a file to Wix Media Manager using an external URL. Use when you need to add a file from an external source to the Media Manager. Note: imported files take time to process and are not immediately available (state=PENDING initially).',
		riskLevel: 'write',
	},
	// ── automations ───────────────────────────────────────────────────────
	{
		key: 'cancelAutomationEvent',
		group: 'automations',
		name: 'cancelEvent',
		method: 'POST',
		path: '/automations/v1/events/cancel',
		specCode: 'WIX_CANCEL_EVENT',
		description:
			'Tool to cancel any remaining automation actions for a trigger and external entity. Use when you need to stop automation workflows that are no longer relevant (e.g., after an invoice is paid or a form submission is processed).',
		riskLevel: 'write',
	},
	{
		key: 'bulkUpdateStorageItemTags',
		group: 'automations',
		name: 'bulkUpdateStorageItemTags',
		method: 'POST',
		path: '/automations/v1/storage-items/bulk/update-tags',
		specCode: 'WIX_UPDATE_STORAGE_ITEM_TAGS',
		description:
			"Tool to bulk update tags on multiple storage items in Wix automations. Use when you need to set public and/or private tags on multiple storage items at once. Requires 'Set Up Automations' permission.",
		riskLevel: 'write',
	},
	{
		key: 'bulkUpdateStorageItemTagsByFilter',
		group: 'automations',
		name: 'bulkUpdateStorageItemTagsByFilter',
		method: 'POST',
		path: '/automations/v1/storage-items/bulk/update-tags-by-filter',
		specCode: 'WIX_UPDATE_BULK_STORAGE_ITEM_TAGS_BY_FILTER',
		description:
			'Tool to bulk update tags on storage items matching filter criteria. Use when you need to add or remove tags from multiple storage items at once based on filter conditions. If a tag appears in both assign and unassign, it will be assigned. This operation is asynchronous and triggers the Storage Item Tags Modified event.',
		riskLevel: 'write',
	},
	// ── community (moderation, groups, faq, reviews) ──────────────────────
	{
		key: 'checkContent',
		group: 'community',
		name: 'checkContent',
		method: 'POST',
		path: '/moderation/v1/content/check',
		specCode: 'WIX_CHECK_CONTENT',
		description:
			'Tool to check content text against Wix moderation rules. Use when you need to validate user-submitted content for policy violations before publishing or to determine if content requires moderation.',
		riskLevel: 'read',
	},
	{
		key: 'queryModerationRules',
		group: 'community',
		name: 'queryModerationRules',
		method: 'POST',
		path: '/moderation/v1/rules/query',
		specCode: 'WIX_QUERY_MODERATION_RULES',
		description:
			'Tool to retrieve moderation rules with optional filtering, sorting, and pagination. Use when you need to fetch rules that manage user-generated content moderation on a Wix site. Returns up to 1000 rules per request.',
		queryBody: true,
		riskLevel: 'read',
	},
	{
		key: 'updateModerationRule',
		group: 'community',
		name: 'updateModerationRule',
		method: 'PATCH',
		path: '/moderation/v1/rules/{ruleId}',
		specCode: 'WIX_UPDATE_RULE',
		description:
			"Tool to update a moderation rule in Wix Community Feedback Moderation. Use when you need to modify an existing rule's settings such as name, enabled status, or configuration. Requires the current revision number to prevent conflicts.",
		pathParams: ['ruleId'],
		riskLevel: 'write',
	},
	{
		key: 'listGroupRequests',
		group: 'community',
		name: 'listGroupRequests',
		method: 'GET',
		path: '/groups/v1/requests',
		specCode: 'WIX_LIST_GROUP_REQUESTS',
		description:
			'Tool to list group requests across a Wix site. Use when you need to retrieve pending or processed requests for group creation. Only admins can see create group requests; members can access their own requests.',
		queryParams: ['limit', 'offset'],
		riskLevel: 'read',
	},
	{
		key: 'queryGroupRequests',
		group: 'community',
		name: 'queryGroupRequests',
		method: 'POST',
		path: '/groups/v1/requests/query',
		specCode: 'WIX_QUERY_GROUP_REQUESTS',
		description:
			'Tool to query group creation requests with filtering, sorting, and pagination. Use when you need to retrieve pending, approved, or rejected group requests from site members.',
		queryBody: true,
		riskLevel: 'read',
	},
	{
		key: 'deleteFaqCategory',
		group: 'community',
		name: 'deleteFaqCategory',
		method: 'DELETE',
		path: '/faq/v1/categories/{categoryId}',
		specCode: 'WIX_DELETE_CATEGORY',
		description:
			'Tool to delete an FAQ category from the Wix site. Deleting a category permanently removes it and all associated questions from the FAQ page. Triggers a Category Deleted event.',
		pathParams: ['categoryId'],
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'deleteQuestionEntry',
		group: 'community',
		name: 'deleteQuestionEntry',
		method: 'DELETE',
		path: '/faq/v1/questions/{questionId}',
		specCode: 'WIX_DELETE_QUESTION_ENTRY',
		description:
			'Tool to delete a question entry from Wix FAQ app. Use when you need to permanently remove a FAQ question entry by its ID.',
		pathParams: ['questionId'],
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'updateQuestionEntryLabels',
		group: 'community',
		name: 'updateQuestionEntryLabels',
		method: 'POST',
		path: '/faq/v1/questions/{questionId}/labels',
		specCode: 'WIX_UPDATE_LABELS',
		description:
			'Tool to set labels for a Wix FAQ question entry. Use when a question entry is updated and you need to modify its labels. This operation replaces all existing labels with the provided list.',
		pathParams: ['questionId'],
		riskLevel: 'write',
	},
	{
		key: 'updateReviewModerationStatus',
		group: 'community',
		name: 'updateReviewModerationStatus',
		method: 'POST',
		path: '/reviews/v1/reviews/{reviewId}/moderate',
		specCode: 'WIX_UPDATE_REVIEWS_MODERATE',
		description:
			'Tool to update the moderation status of a review. Use when you need to approve, reject, or change the moderation status of a specific review.',
		pathParams: ['reviewId'],
		riskLevel: 'write',
	},
	{
		key: 'bulkUpdateReviewModerationStatus',
		group: 'community',
		name: 'bulkUpdateReviewModerationStatus',
		method: 'POST',
		path: '/reviews/v1/reviews/bulk/moderate',
		specCode: 'WIX_UPDATE_REVIEWS_MODERATE2',
		description:
			'Tool to bulk update the moderation status of multiple reviews at once. All filtered reviews are updated to the same moderation status. Use when you need to moderate multiple reviews efficiently instead of updating them one by one.',
		riskLevel: 'write',
	},
	// ── portfolio ─────────────────────────────────────────────────────────
	{
		key: 'deleteProject',
		group: 'portfolio',
		name: 'deleteProject',
		method: 'DELETE',
		path: '/portfolio/v1/projects/{projectId}',
		specCode: 'WIX_DELETE_PROJECT',
		description:
			'Tool to delete a project from Wix Portfolio. Use when you need to remove a specific project by its ID. Note: This operation may return an empty success response when the Portfolio app is not installed.',
		pathParams: ['projectId'],
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'deleteProjectItem',
		group: 'portfolio',
		name: 'deleteProjectItem',
		method: 'DELETE',
		path: '/portfolio/v1/projects/items/{itemId}',
		specCode: 'WIX_DELETE_PROJECT_ITEM',
		description:
			'Tool to delete a project item from the Wix Portfolio. Use when you need to permanently remove a portfolio project item by its ID.',
		pathParams: ['itemId'],
		riskLevel: 'destructive',
		irreversible: true,
	},
	// ── benefits ──────────────────────────────────────────────────────────
	{
		key: 'bulkDeleteBenefitItems',
		group: 'benefits',
		name: 'bulkDeleteBenefitItems',
		method: 'POST',
		path: '/benefit-programs/v1/items/bulk/delete',
		specCode: 'WIX_DELETE_BENEFIT_ITEMS',
		description:
			'Tool to bulk delete benefit items from Wix Benefit Programs. Use when you need to remove multiple benefit items at once by providing their IDs.',
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'bulkDeleteBenefitItemsByFilter',
		group: 'benefits',
		name: 'bulkDeleteBenefitItemsByFilter',
		method: 'POST',
		path: '/benefit-programs/v1/items/bulk/delete-by-filter',
		specCode: 'WIX_DELETE_ITEMS_BY_FILTER',
		description:
			'Tool to bulk delete benefit program items by filter criteria. Use when you need to delete multiple items matching specific conditions within a namespace. If no filter is provided, this may delete all items in the namespace.',
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'bulkDeletePoolDefinitions',
		group: 'benefits',
		name: 'bulkDeletePoolDefinitions',
		method: 'POST',
		path: '/benefit-programs/v1/pools/definitions/bulk/delete',
		specCode: 'WIX_DELETE_POOL_DEFINITIONS_BULK',
		description:
			'Tool to bulk delete pool definitions from Wix Benefit Programs. Use when you need to remove multiple pool definitions by their IDs in a single operation.',
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'deleteProgramDefinition',
		group: 'benefits',
		name: 'deleteProgramDefinition',
		method: 'DELETE',
		path: '/benefit-programs/v1/programs/definitions/{definitionId}',
		specCode: 'WIX_DELETE_PROGRAM_DEFINITION',
		description:
			'Tool to delete a program definition from Wix Benefit Programs. Use when you need to permanently remove a benefit program definition by its ID.',
		pathParams: ['definitionId'],
		riskLevel: 'destructive',
		irreversible: true,
	},
	// ── multilingual ──────────────────────────────────────────────────────
	{
		key: 'bulkDeleteTranslationContent',
		group: 'multilingual',
		name: 'bulkDeleteTranslationContent',
		method: 'POST',
		path: '/multilingual/v1/content/bulk/delete',
		specCode: 'WIX_DELETE_BULK_CONTENT',
		description:
			'Tool to bulk delete translation content by IDs. Use when you need to delete multiple translation content items in a single operation.',
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'bulkUpdateTranslationContentByKey',
		group: 'multilingual',
		name: 'bulkUpdateTranslationContentByKey',
		method: 'POST',
		path: '/multilingual/v1/content/bulk/update-by-key',
		specCode: 'WIX_UPDATE_CONTENT_BY_KEY_BULK',
		description:
			'Tool to bulk update translation content by composite key (schemaId, entityId, locale). Use when updating translatable fields for multiple content items identified by their schema, entity, and locale combination. Triggers Content Updated event on success.',
		riskLevel: 'write',
	},
	// ── system (apps, secrets, dashboard, branches) ───────────────────────
	{
		key: 'getAppInstance',
		group: 'system',
		name: 'getAppInstance',
		method: 'GET',
		path: '/apps/v1/instance',
		specCode: 'WIX_GET_APP_INSTANCE',
		description:
			'Tool to retrieve the current app instance details and associated site information. Use when you need to fetch app configuration, permissions, or site details.',
		riskLevel: 'read',
	},
	{
		key: 'listAppPermissions',
		group: 'system',
		name: 'listAppPermissions',
		method: 'GET',
		path: '/apps/v1/permissions',
		specCode: 'WIX_LIST_APP_PERMISSIONS',
		description:
			'Tool to retrieve all permissions for a specified Wix app. Use when you need to list the permissions your app requests when users install it on a site.',
		queryParams: ['appId'],
		riskLevel: 'read',
	},
	{
		key: 'listAppPlansByAppId',
		group: 'system',
		name: 'listAppPlansByAppId',
		method: 'GET',
		path: '/apps/v1/apps/{appId}/plans',
		specCode: 'WIX_LIST_APP_PLANS_BY_APP_ID',
		description:
			'Tool to retrieve app plans by application ID, including pricing, tax settings, and currency details. Use when you need to fetch pricing plans for a specific Wix app. Note: Only returns activated plans; externally managed plans are excluded. For yearly plans, returns monthly payment amount (multiply by 12 for total).',
		pathParams: ['appId'],
		riskLevel: 'read',
	},
	{
		key: 'getPurchaseHistory',
		group: 'system',
		name: 'getPurchaseHistory',
		method: 'GET',
		path: '/apps/v1/purchase-history',
		specCode: 'WIX_GET_PURCHASE_HISTORY',
		description:
			'Tool to retrieve purchase history for your app on a site. Use when you need to view past purchases and verify upgrades. Note: The response does not include cancellation details. Site context is automatically derived from authentication.',
		riskLevel: 'read',
	},
	{
		key: 'deleteSecret',
		group: 'system',
		name: 'deleteSecret',
		method: 'DELETE',
		path: '/secrets/v1/secrets/{secretId}',
		specCode: 'WIX_DELETE_SECRET',
		description:
			'Tool to delete a secret from Wix Secrets Vault. Use when you need to permanently remove a secret by its GUID identifier.',
		pathParams: ['secretId'],
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'deleteUserFavorite',
		group: 'system',
		name: 'deleteUserFavorite',
		method: 'DELETE',
		path: '/dashboard/v1/favorites/{pageId}',
		specCode: 'WIX_DELETE_USER_FAVORITE',
		description:
			"Tool to remove a dashboard page from the current user's list of favorite pages. Use when you need to delete a specific favorite from the user's dashboard. The API exhibits idempotent behavior - returns success even if the favorite doesn't exist.",
		pathParams: ['pageId'],
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'bulkDeleteReportsByFilter',
		group: 'system',
		name: 'bulkDeleteReportsByFilter',
		method: 'POST',
		path: '/dashboard/v1/reports/bulk/delete-by-filter',
		specCode: 'WIX_DELETE_REPORTS_BY_FILTER',
		description:
			'Tool to bulk delete reports from the dashboard by filter criteria. Use when you need to remove multiple reports matching specific conditions. Triggers a Report Deleted event for each removed report.',
		riskLevel: 'destructive',
		irreversible: true,
	},
	{
		key: 'updateOperationGroupTagsByFilter',
		group: 'system',
		name: 'updateOperationGroupTagsByFilter',
		method: 'POST',
		path: '/branches/v1/operation-groups/bulk/update-tags-by-filter',
		specCode: 'WIX_UPDATE_OPERATION_GROUP_TAGS_BY_FILTER',
		description:
			'Tool to bulk update tags on operation groups using filter criteria. Use when you need to add or remove tags from multiple operation groups matching specific conditions. If a tag appears in both assign and unassign, it will be assigned.',
		riskLevel: 'write',
	},
];
